import fs from 'node:fs';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
const store={prepare(query){let args=[];return {bind(...values){args=values;return this},async first(){return sql.prepare(query).get(...args)??null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}}}}}};
let user=null;const api={};const source=ts.transpileModule(fs.readFileSync('app/api/friends/route.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
new Function('require','exports',source)(name=>name==='@/app/auth'?{getUser:async()=>user}:name==='@/db/raw'?{db:()=>store}:{limited:async()=>false,audit:async()=>{}},api);
const request=async body=>{const response=await api.POST(new Request('https://test.example/api/friends',{method:'POST',headers:{origin:'https://test.example','Content-Type':'application/json'},body:JSON.stringify(body)}));return {status:response.status,data:await response.json()}};
assert.equal((await request({action:'list'})).status,403);
user={userId:'a'};assert.equal((await request({action:'list'})).status,403);
for(const id of ['a','b','c'])sql.prepare('INSERT INTO accounts(id,email,name,created,updated) VALUES(?,?,?,?,?)').run(id,id+'@example.test',id,1,1);
const a=(await request({action:'list'})).data;assert.equal(a.code.length,16);assert.equal((await request({action:'request',code:a.code})).status,400);
user={userId:'b'};const b=(await request({action:'list'})).data;user={userId:'a'};
assert.equal((await request({action:'request',code:b.code})).status,200);await request({action:'request',code:b.code});
const row=(await request({action:'list'})).data.friends;assert.equal(row.length,1);assert.equal(row[0].outgoing,1);assert.equal((await request({action:'accept',id:row[0].id})).status,403);
user={userId:'c'};assert.equal((await request({action:'list'})).data.friends.length,0);assert.equal((await request({action:'accept',id:row[0].id})).status,403);assert.equal((await request({action:'remove',id:row[0].id})).status,403);
user={userId:'b'};await request({action:'request',code:a.code});assert.equal((await request({action:'list'})).data.friends.length,1);assert.equal((await request({action:'accept',id:row[0].id})).status,200);
user={userId:'a'};assert.equal((await request({action:'list'})).data.friends[0].state,'accepted');assert.equal((await request({action:'remove',id:row[0].id})).status,200);
assert.equal((await request({action:'list'})).data.friends.length,0);
console.log('PASS: account requirement, private lists, request deduplication, recipient-only acceptance, participant-only removal.');
