import fs from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
const source=ts.transpileModule(fs.readFileSync('app/media/ice-signaling.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
const exports={};new Function('exports',source)(exports);
const {receiveIce,drainIce,matchesGeneration}=exports;
const accepted=[];
const peer={generation:'new',pending:[],pc:{signalingState:'stable',remoteDescription:null,async addIceCandidate(c){if(c?.candidate==='bad')throw Object.assign(new Error('Rejected'),{name:'OperationError'});accepted.push(c)}}};
await receiveIce(peer,{candidate:'bad'},'new');
await receiveIce(peer,{candidate:'good',usernameFragment:'current'},'new');
assert.equal(peer.pending.length,2);
assert.equal(accepted.length,0);
peer.pc.remoteDescription={sdp:'v=0\r\na=ice-ufrag:current\r\n'};
await drainIce(peer);
assert.equal(peer.iceRejected,1);
assert.equal(accepted[0].candidate,'good');
assert.equal(peer.pending.length,0);
await receiveIce(peer,{candidate:'old'},'old');
await receiveIce(peer,{candidate:'old',usernameFragment:'expired'},'new');
assert.equal(accepted.length,1);
await receiveIce(peer,null,'new');
assert.equal(accepted.length,2);
assert.equal(matchesGeneration(peer,'old'),false);
assert.equal(matchesGeneration(peer,undefined),true); // Older clients during rollout.
peer.pc.signalingState='closed';
await receiveIce(peer,{candidate:'closed'},'new');
assert.equal(accepted.length,2);
peer.pc.signalingState='stable';peer.pc.remoteDescription=null;
for(let i=0;i<300;i++)await receiveIce(peer,{candidate:'queued'},'new');
assert.equal(peer.pending.length,256);
console.log('PASS: ICE buffering, rejected-candidate isolation, stale generations/ufrags, end marker, closed peer and queue bound.');
