'use client';
import {useEffect,useRef,useState} from 'react';
import {AudioLines,ArrowUpRight,Users,Presentation,Mic,MicOff,MonitorUp,MonitorOff,Link as LinkIcon,LogOut,Download,Headphones,Maximize2,Volume2,Check,Radio,ShieldCheck,Settings2,Camera,CameraOff} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';

import Settings, {CameraView} from './media/settings';
import {useDevices} from './media/use-devices';
import {routeAudio,mediaError} from './media/audio';

type Room={id:string;title:string;mode:'conversation'|'presentation';host:string};
type Member={id:string;name:string;mic:number;screen:number;camera:number};
type Session={room:Room;id:string;token:string};
type Peer={pc:RTCPeerConnection;mic:RTCRtpTransceiver;video:RTCRtpTransceiver;sound:RTCRtpTransceiver;camera:RTCRtpTransceiver;pending:RTCIceCandidateInit[];stream:MediaStream};
async function api(body:Record<string,unknown>){const r=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Object.assign(new Error(d.error||'Não foi possível conectar.'),{status:r.status});return d;}
const initials=(name:string)=>name.split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function Media({stream,output,volume,onBlocked,onError}:{stream:MediaStream;output:string;volume:number;onBlocked:()=>void;onError:(e:unknown)=>void}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{const el=ref.current;if(el){el.srcObject=stream;el.play().catch(onBlocked);}return()=>{if(el)el.srcObject=null}},[stream]);useEffect(()=>{if(ref.current)void routeAudio(ref.current,output,volume).catch(onError)},[output,volume]);return <video ref={ref} autoPlay playsInline/>}

export default function Home(){
 const [name,setName]=useState(''),[title,setTitle]=useState('Minha sala'),[mode,setMode]=useState('conversation'),[tab,setTab]=useState('create'),[invite,setInvite]=useState('');
 const [session,setSession]=useState<Session|null>(null),[members,setMembers]=useState<Member[]>([]),[remote,setRemote]=useState<Record<string,MediaStream>>({}),[states,setStates]=useState<Record<string,string>>({});
 const [screen,setScreen]=useState<MediaStream|null>(null),[busy,setBusy]=useState(false),[mediaBusy,setMediaBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false),[blocked,setBlocked]=useState(false),[installOpen,setInstallOpen]=useState(false),[installEvent,setInstallEvent]=useState<any>(null),[selected,setSelected]=useState<string|null>(null),[connected,setConnected]=useState(true);
 const current=useRef<Session|null>(null),peers=useRef(new Map<string,Peer>()),display=useRef<MediaStream|null>(null),cursor=useRef(0),signalQueue=useRef(Promise.resolve());
 const [remoteCameras,setRemoteCameras]=useState<Record<string,MediaStream>>({});
 const media=useDevices({onMic:async track=>{await Promise.all([...peers.current.values()].filter(p=>p.pc.signalingState!=='closed').map(p=>p.mic.sender.replaceTrack(track)))},onCamera:async track=>{await Promise.all([...peers.current.values()].filter(p=>p.pc.signalingState!=='closed').map(p=>p.camera.sender.replaceTrack(track)))}});
 const {mic,micEnabled,micStream}=media;
 const hosting=session?.id===session?.room.host,canSend=!!session&&(hosting||session.room.mode==='conversation');
 function fail(e:unknown){setError(e instanceof Error?e.message:'Não foi possível concluir. Tente novamente.');}
 function cleanup(){current.current=null;for(const p of peers.current.values())p.pc.close();peers.current.clear();media.stopAll();display.current?.getTracks().forEach(t=>t.stop());display.current=null;cursor.current=0;setScreen(null);setRemote({});setRemoteCameras({});setMembers([]);setStates({});setSelected(null);}
 useEffect(()=>{const params=new URLSearchParams(location.hash.slice(1));const id=params.get('sala');if(id){setInvite(location.href);setTab('join');}if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const fn=(e:Event)=>{e.preventDefault();setInstallEvent(e)};window.addEventListener('beforeinstallprompt',fn);return()=>{window.removeEventListener('beforeinstallprompt',fn);cleanup()}},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'get_room_status',description:'Consulta o modo e os participantes da sala aberta. Não liga microfone nem captura tela.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Entrada inválida');return {inRoom:!!session,title:session?.room.title??null,mode:session?.room.mode??null,participants:members.map(m=>({name:m.name,microphone:!!m.mic,screen:!!m.screen}))}}} ,{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[session,members]);
 function send(target:string,payload:unknown){const s=current.current;if(!s)return Promise.resolve();const task=signalQueue.current.catch(()=>{}).then(async()=>{if(current.current!==s)return;await api({...s,room:s.room.id,action:'signal',target,payload})});signalQueue.current=task;return task;}
 function createPeer(m:Member,s:Session){
  const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]});
  const direction:RTCRtpTransceiverDirection=s.room.mode==='conversation'?'sendrecv':s.id===s.room.host?'sendonly':'recvonly';
  const p:Peer={pc,mic:pc.addTransceiver('audio',{direction}),video:pc.addTransceiver('video',{direction}),sound:pc.addTransceiver('audio',{direction}),camera:pc.addTransceiver('video',{direction}),pending:[],stream:new MediaStream()};peers.current.set(m.id,p);
  if(direction!=='recvonly'){const a=micStream.current?.getAudioTracks()[0],v=display.current?.getVideoTracks()[0],da=display.current?.getAudioTracks()[0];if(a)void p.mic.sender.replaceTrack(a);const cam=media.cameraEnabled.current?media.cameraStream.current?.getVideoTracks()[0]:null;if(cam)void p.camera.sender.replaceTrack(cam);if(v)void p.video.sender.replaceTrack(v);if(da)void p.sound.sender.replaceTrack(da);}
  pc.onicecandidate=e=>{if(e.candidate)void send(m.id,{type:'candidate',candidate:e.candidate.toJSON()}).catch(fail)};
  pc.ontrack=e=>{if(s.room.mode==='presentation'&&m.id!==s.room.host)return;if(e.transceiver===p.camera){setRemoteCameras(prev=>({...prev,[m.id]:new MediaStream([e.track])}));return}p.stream.addTrack(e.track);setRemote(prev=>({...prev,[m.id]:p.stream}));};
  pc.onconnectionstatechange=()=>{if(current.current!==s)return;setStates(prev=>({...prev,[m.id]:pc.connectionState}));};
  if(s.id<m.id)void (async()=>{await pc.setLocalDescription(await pc.createOffer());await send(m.id,{type:'offer',sdp:pc.localDescription?.sdp})})().catch(fail);
  return p;
 }
 useEffect(()=>{
  if(!session)return;let stopped=false,timer:ReturnType<typeof setTimeout>;const s=session;current.current=s;
  async function poll(){
   try{const data=await api({...s,room:s.room.id,action:'poll',mic:micEnabled.current,screen:!!display.current,camera:media.cameraEnabled.current,cursor:cursor.current});if(stopped)return;setConnected(true);setMembers(data.members);
    const eligible:Member[]=data.members.filter((m:Member)=>m.id!==s.id&&(s.room.mode==='conversation'||s.id===s.room.host||m.id===s.room.host));
    for(const m of eligible)if(!peers.current.has(m.id))createPeer(m,s);
    for(const [id,p] of peers.current)if(!eligible.some(m=>m.id===id)){p.pc.close();peers.current.delete(id);setRemoteCameras(prev=>{const next={...prev};delete next[id];return next});setRemote(prev=>{const next={...prev};delete next[id];return next});}
    for(const msg of data.signals){if(stopped)return;cursor.current=msg.id;const p=peers.current.get(msg.sender);if(p){const v=JSON.parse(msg.payload);try{if(v.type==='candidate'){if(p.pc.remoteDescription)await p.pc.addIceCandidate(v.candidate);else p.pending.push(v.candidate)}else{if(v.type==='answer'&&p.pc.signalingState!=='have-local-offer')continue;if(v.type==='offer'&&p.pc.remoteDescription?.sdp===v.sdp)continue;await p.pc.setRemoteDescription({type:v.type,sdp:v.sdp});for(const c of p.pending)await p.pc.addIceCandidate(c);p.pending=[];if(v.type==='offer'){await p.pc.setLocalDescription(await p.pc.createAnswer());await send(msg.sender,{type:'answer',sdp:p.pc.localDescription?.sdp})}}}catch(e){console.error(e);setError('A conexão com um participante falhou. Saia e entre novamente.')}}cursor.current=msg.id;}
   }catch(e:any){if(stopped)return;setConnected(false);if(e.status===401||e.status===404){cleanup();setSession(null);fail(e);return;}}
   if(!stopped)timer=setTimeout(poll,1500);
  }
  void poll();return()=>{stopped=true;clearTimeout(timer)};
 },[session]);
 async function enter(create:boolean){setBusy(true);setError('');try{if(!window.RTCPeerConnection)throw new Error('Este navegador não oferece suporte a chamadas. Abra no Chrome ou Edge atualizado.');let room=invite.trim();if(!create){try{const u=new URL(room);room=new URLSearchParams(u.hash.slice(1)).get('sala')||''}catch{}if(!/^[a-f0-9]{32}$/.test(room))throw new Error('Cole o link completo do convite.');}
 const data=await api(create?{action:'create',name,title,mode}:{action:'join',name,room});cleanup();current.current=data;setSession(data);setConnected(true);setBlocked(false);history.replaceState(null,'',`/#sala=${data.room.id}`);
 }catch(e){fail(e)}finally{setBusy(false)}}
 async function toggleMic(){if(canSend)await media.toggleMic()}
 async function stopScreen(){const old=display.current;display.current=null;setScreen(null);old?.getTracks().forEach(t=>t.stop());await Promise.all([...peers.current.values()].map(async p=>{await p.video.sender.replaceTrack(null);await p.sound.sender.replaceTrack(null)})).catch(fail)}
 async function toggleScreen(){if(!canSend||mediaBusy)return;if(display.current){await stopScreen();return}setMediaBusy(true);setError('');try{if(!navigator.mediaDevices?.getDisplayMedia)throw new Error('Compartilhamento de tela indisponível neste dispositivo. Use Chrome ou Edge no computador.');const stream=await navigator.mediaDevices.getDisplayMedia({video:{width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:15,max:30}},audio:true});if(!current.current){stream.getTracks().forEach(t=>t.stop());return}display.current=stream;setScreen(stream);setSelected(session!.id);stream.getVideoTracks()[0].onended=()=>void stopScreen();for(const p of peers.current.values()){await p.video.sender.replaceTrack(stream.getVideoTracks()[0]);await p.sound.sender.replaceTrack(stream.getAudioTracks()[0]??null)}}catch(e:any){if(e.name!=='NotAllowedError')fail(e)}finally{setMediaBusy(false)}}
 async function leave(){const s=current.current;if(!s)return;setBusy(true);try{await api({...s,room:s.room.id,action:'leave'});cleanup();setSession(null);history.replaceState(null,'','/');setError('')}catch(e){fail(e)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(`${location.origin}/#sala=${session!.room.id}`);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('Não foi possível copiar. Copie o endereço desta página.')}}
 async function install(){if(installEvent){await installEvent.prompt();setInstallEvent(null)}else setInstallOpen(true)}
 const people=members.map(m=>m.id===session?.id?{...m,mic:mic?1:0,screen:screen?1:0,camera:media.cameraLive?1:0}:m);
 const shares=people.filter(m=>m.screen);const focus=shares.find(m=>m.id===selected)??shares[0];
 const focusStream=focus?.id===session?.id?screen:focus?remote[focus.id]:null;
 return <div className="app-shell">
  <header className="topbar"><a className="brand" href="/" onClick={e=>{if(session)e.preventDefault()}} aria-label="Sala, início"><span className="brand-icon"><AudioLines size={25}/></span><span>sala<span className="brand-period">.</span></span></a><span className="top-caption">VOZ & TELA</span><button className="settings-button" onClick={()=>media.setPanel(true)}><Settings2 size={17}/><span>Configurações</span></button><button className="install-button" onClick={install}><Download size={16}/><span>Instalar aplicativo</span></button></header>
  <main className={session?'in-room':'lobby'}>
   {!session?<><section className="welcome"><span className="eyebrow">UM LUGAR PARA SE CONECTAR</span><h1>Uma sala.<br/>Sua voz.<br/><span>Todo mundo junto.</span></h1><p>Abra uma conversa ou apresente sua tela.<br/>Convide as pessoas e deixe o papo acontecer.</p><div className="welcome-foot"><Headphones size={21}/><span>Use fones para conversar sem eco.</span></div><div className="feature-line"><span><Mic size={16}/> Áudio ao vivo</span><span><MonitorUp size={16}/> Tela compartilhada</span></div></section>
   <section className="entry-card"><div className="entry-heading"><span className="small-icon"><Radio size={22}/></span><div><h2>Vamos nos encontrar?</h2><p>Sua próxima conversa começa aqui.</p></div></div>
   <Tabs value={tab} onValueChange={setTab}><TabsList className="entry-tabs"><TabsTrigger value="create">Criar uma sala</TabsTrigger><TabsTrigger value="join">Entrar com convite</TabsTrigger></TabsList>
   <label className="field">Seu nome<input value={name} onChange={e=>setName(e.target.value)} maxLength={40} placeholder="Como você quer aparecer?" autoComplete="nickname"/></label>
   <TabsContent value="create"><form onSubmit={e=>{e.preventDefault();void enter(true)}}><label className="field">Nome da sala<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={70} required placeholder="Ex.: Conversa da equipe"/></label>
    <label className="field-label">Como vai ser?</label><RadioGroup value={mode} onValueChange={setMode} className="mode-group"><label className={'mode-option '+(mode==='conversation'?'active':'')}><Users size={22}/><span><strong>Conversa em grupo</strong><small>Todos podem falar e mostrar a tela.</small></span><RadioGroupItem value="conversation" aria-label="Conversa em grupo"/></label><label className={'mode-option '+(mode==='presentation'?'active':'')}><Presentation size={22}/><span><strong>Apresentação</strong><small>Você transmite. A plateia acompanha.</small></span><RadioGroupItem value="presentation" aria-label="Apresentação"/></label></RadioGroup>
    <button className="primary wide" disabled={busy||!name.trim()||!title.trim()}>{busy?'Abrindo sala…':'Criar sala'}<ArrowUpRight size={19}/></button></form></TabsContent>
   <TabsContent value="join"><form onSubmit={e=>{e.preventDefault();void enter(false)}}><label className="field">Link do convite<input value={invite} onChange={e=>setInvite(e.target.value)} placeholder="Cole aqui o link da sala" required/></label><p className="join-note">Você entra com o microfone desligado. Ative quando estiver pronto para falar.</p><button className="primary wide" disabled={busy||!name.trim()||!invite.trim()}>{busy?'Entrando…':'Entrar na sala'}<ArrowUpRight size={19}/></button></form></TabsContent></Tabs><div className="card-footer"><ShieldCheck size={15}/><span>Sem gravação · Até 6 pessoas por sala</span></div></section></>:<>
    <div className="room-heading"><div><span className="eyebrow">{hosting?'SUA SALA':session.room.mode==='presentation'?'VOCÊ ESTÁ NA PLATEIA':'SALA DE CONVERSA'}</span><h1>{session.room.title}</h1></div><div className="room-info"><span className="mode-badge">{session.room.mode==='conversation'?<Users size={16}/>:<Presentation size={16}/>} {session.room.mode==='conversation'?'Conversa':'Apresentação'}</span><button className="secondary" onClick={copy}>{copied?<Check size={17}/>:<LinkIcon size={17}/>} {copied?'Link copiado':'Convidar'}</button></div></div>
    <div className="room-layout"><section className="stage"><div className="stage-top"><span>{focus?`${focus.name} está compartilhando`:'Tela compartilhada'}</span>{focus&&<button aria-label="Ver tela em tamanho máximo" className="icon-button" onClick={()=>document.querySelector('.stage')?.requestFullscreen().catch(fail)}><Maximize2 size={18}/></button>}</div><div className="stage-content">{focusStream?<video className="main-screen" autoPlay muted playsInline ref={el=>{if(el&&el.srcObject!==focusStream){el.srcObject=focusStream;void el.play().catch(()=>{})}}}/>:<div className="stage-empty"><span className="stage-symbol"><MonitorUp size={38} strokeWidth={1.3}/></span><h2>{canSend?'Sua tela também faz parte da conversa.':'A apresentação vai começar.'}</h2><p>{canSend?'Compartilhe uma janela, uma aba ou a tela inteira.':'Aguarde o anfitrião ligar o microfone ou compartilhar a tela.'}</p>{canSend&&<button className="secondary" onClick={toggleScreen} disabled={mediaBusy}><MonitorUp size={17}/> Compartilhar tela</button>}</div>}</div><div className="stage-bottom"><span><Users size={15}/> {people.length} de 6 pessoas</span><span>{connected?'Sala conectada':'Tentando reconectar…'}</span></div></section>
    <aside className="people-panel"><div className="panel-title"><h2>Na sala</h2><span>{people.length}</span></div><div className="people-list">{people.map((m,i)=><div className="person" key={m.id}><span className={'avatar color-'+i%4}>{initials(m.name)}</span><div className="person-label"><strong>{m.name}{m.id===session.id?' (você)':''}</strong><small>{m.id===session.room.host?'Anfitrião':session.room.mode==='presentation'?'Plateia':m.id===session.id?'Conectado':states[m.id]==='connected'?'Conectado':states[m.id]==='failed'?'Falha na conexão':'Conectando…'}</small></div>{m.mic?<Mic size={16} className="mic-on"/>:<MicOff size={16} className="muted"/>}</div>)}</div>{shares.length>0&&<div className="share-list"><h3>Telas disponíveis</h3>{shares.map(m=><button key={m.id} className={focus?.id===m.id?'chosen':''} onClick={()=>setSelected(m.id)}><MonitorUp size={16}/><span>{m.name}</span></button>)}</div>}<div className="invite-note"><LinkIcon size={20}/><p>A conversa fica melhor com companhia.</p><button onClick={copy}>{copied?'Copiado!':'Copiar convite'} <ArrowUpRight size={15}/></button></div></aside></div>
    <div className="camera-strip">{people.filter(m=>m.camera).map(m=>{const stream=m.id===session.id?media.camera:remoteCameras[m.id];return stream?<div className="camera-tile" key={m.id}><CameraView stream={stream} mirror={m.id===session.id&&media.prefs.mirror}/><span>{m.name}{m.id===session.id?" (você)":""}</span></div>:null})}</div><div className="media-elements">{Object.entries(remote).map(([id,stream])=><Media key={id} stream={stream} output={media.prefs.output} volume={media.prefs.volume} onBlocked={()=>setBlocked(true)} onError={e=>media.setError(mediaError(e))}/>)}</div>
    {blocked&&<button className="audio-unlock" onClick={()=>{Promise.all([...document.querySelectorAll('video')].map(v=>v.play())).then(()=>setBlocked(false)).catch(()=>setError('Clique novamente para liberar o áudio.'))}}><Volume2 size={18}/> Clique para ouvir a sala</button>}
    <div className="controls"><div className="control-hint"><Headphones size={18}/><span>{canSend?'Seu espaço de conversa':'Acompanhando a apresentação'}</span></div><div className="control-buttons">{canSend&&<><button className={'control '+(mic?'enabled':'')} onClick={toggleMic} disabled={media.busy} aria-pressed={mic}>{mic?<Mic size={21}/>:<MicOff size={21}/>}<span>{mic?'Silenciar':'Ligar microfone'}</span></button><button className={'control '+(media.cameraLive?'enabled':'')} onClick={media.toggleCamera} disabled={media.busy} aria-pressed={media.cameraLive}>{media.cameraLive?<CameraOff size={21}/>:<Camera size={21}/>}<span>{media.cameraLive?'Desligar câmera':'Ligar câmera'}</span></button><button className={'control '+(screen?'enabled':'')} onClick={toggleScreen} disabled={mediaBusy} aria-pressed={!!screen}>{screen?<MonitorOff size={21}/>:<MonitorUp size={21}/>}<span>{screen?'Parar tela':'Compartilhar'}</span></button></>}<button className="control leave" disabled={busy} onClick={leave}><LogOut size={21}/><span>{hosting?'Encerrar sala':'Sair da sala'}</span></button></div></div>
   </>}
   {media.error&&!media.open&&<div className="error" role="alert"><span>{media.error}</span><button onClick={()=>media.setError('')} aria-label="Fechar aviso">×</button></div>}{error&&<div className="error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Fechar aviso">×</button></div>}
  </main><footer className="site-footer"><span>SALA · VOZ & TELA</span><span>{session?'Salas expiram após 12 horas.':'No navegador ou instalado no seu computador.'}</span><span>VERSÃO INICIAL</span></footer>
  <Settings m={media}/><Dialog open={installOpen} onOpenChange={setInstallOpen}><DialogContent className="install-dialog"><DialogHeader><DialogTitle>Instalar no Windows</DialogTitle><DialogDescription>Abra este endereço no Microsoft Edge ou Google Chrome.</DialogDescription></DialogHeader><ol><li>No menu do navegador, procure <strong>Aplicativos → Instalar este site como aplicativo</strong> (Edge) ou a opção <strong>Instalar Sala</strong> (Chrome).</li><li>Confirme a instalação. O Sala abrirá em uma janela própria, com atalho no Windows.</li></ol><p>Esta é uma instalação pelo navegador. Você precisa de internet para participar das salas.</p></DialogContent></Dialog>
 </div>
}
