'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {AudioLines,ArrowUpRight,Users,Presentation,Mic,MicOff,MonitorUp,MonitorOff,Link as LinkIcon,LogOut,Download,Headphones,Maximize2,Volume2,Check,Radio,ShieldCheck,Settings2,Camera,CameraOff,Pencil,Video} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';

import {readRooms,writeRooms,localId,type SavedRoom} from './media/saved-rooms';
import ReportParticipant from './media/report-participant';
import {preferScreenQuality,screenQualityLabel,setScreenSenderQuality,type ScreenQuality} from './media/screen-quality';
import type {RecordingAudioSource} from './media/recording-audio';
import ParticipantOptions, {SelfOptions} from './media/participant-options';
import {useParticipantPrefs} from './media/use-participant-prefs';
import {participantVolume} from './media/participant-audio';
import {useRecordings,RecordingsPanel,type RecordRequest} from './media/recordings';
import ProgramSettings from './media/program-settings';
import RoomChat from './media/room-chat';
import MicIndicator from './media/mic-indicator';
import Settings, {CameraView} from './media/settings';
import {useDevices} from './media/use-devices';
import {routeAudio,mediaError} from './media/audio';
import {prepareChannels,attachChannels,type Channels} from './media/peer';

type Room={id:string;title:string;mode:'conversation'|'presentation';host:string};
type Member={id:string;name:string;mic:number;screen:number;camera:number;recording:number};
type Session={room:Room;id:string;token:string};
type Peer=Channels&{pc:RTCPeerConnection;pending:RTCIceCandidateInit[];stream:MediaStream;quality?:ScreenQuality;limited?:boolean;bad?:number;good?:number;created?:number;disconnectedAt?:number};
async function api(body:Record<string,unknown>){const r=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});const d:any=await r.json();if(!r.ok)throw Object.assign(new Error(d.error||'Não foi possível conectar.'),{status:r.status});return d;}
const initials=(name:string)=>name.split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function Media({stream,output,volume,onBlocked,onError}:{stream:MediaStream;output:string;volume:number;onBlocked:()=>void;onError:(e:unknown)=>void}){const ref=useRef<HTMLAudioElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;const play=()=>void el.play().catch(onBlocked);el.srcObject=stream;const tracks=stream.getAudioTracks();tracks.forEach(t=>t.addEventListener('unmute',play));play();return()=>{tracks.forEach(t=>t.removeEventListener('unmute',play));el.pause();el.srcObject=null}},[stream]);useEffect(()=>{if(ref.current)void routeAudio(ref.current,output,volume).catch(onError)},[output,volume]);return <audio ref={ref} autoPlay muted={volume===0}/>}

type Workspace={key:string;saved:SavedRoom|null;status:string;unread:number};
export default function Home({accountId}:{accountId?:string}){
 const recordings=useRecordings();
 const [rooms,setRooms]=useState<Workspace[]>([]),[active,setActive]=useState(''),[ready,setReady]=useState(false),[storageError,setStorageError]=useState('');
 const roomsRef=useRef(rooms);roomsRef.current=rooms;
 useEffect(()=>{const saved=readRooms(accountId);const list:Workspace[]=saved.map(saved=>({key:saved.room.id,saved,status:'Recuperando…',unread:0}));const invitation=new URLSearchParams(location.hash.slice(1)).get('sala');if(!list.length||(invitation&&!list.some(r=>r.saved?.room.id===invitation)))list.push({key:localId(),saved:null,status:'Nova sala',unread:0});setRooms(list);setActive(list.find(r=>r.saved?.room.id===invitation)?.key??list.at(-1)!.key);setReady(true)},[]);
 useEffect(()=>{if(ready&&!writeRooms(rooms.flatMap(r=>r.saved?[r.saved]:[]),accountId))setStorageError('Não foi possível salvar as salas neste dispositivo. Guarde os links dos convites para voltar.')},[rooms,ready]);
 const change=useCallback((key:string,saved:SavedRoom|null)=>setRooms(old=>old.map(r=>r.key===key?{...r,saved:saved?{...saved,accountId}:null,status:saved?'Conectada':'Nova sala',unread:0}:r)),[]);
 const status=useCallback((key:string,status:string)=>setRooms(old=>old.map(r=>r.key===key&&r.status!==status?{...r,status}:r)),[]);
 const unread=useCallback((key:string,unread:number)=>setRooms(old=>old.map(r=>r.key===key&&r.unread!==unread?{...r,unread}:r)),[]);
 const existing=useCallback((room:string)=>{const found=roomsRef.current.find(r=>r.saved?.room.id===room);if(found){setActive(found.key);return true}return false},[]);
 function add(){history.replaceState(null,'','/');const draft=rooms.find(r=>!r.saved);if(draft){setActive(draft.key);return}const key=localId();setRooms(old=>[...old,{key,saved:null,status:'Nova sala',unread:0}]);setActive(key)}
 if(!ready)return <div className="rooms-loading">Abrindo suas salas…</div>;
 return <><nav className="rooms-nav" aria-label="Minhas salas"><strong>Minhas salas</strong><div className="room-tabs">{rooms.map(r=><button key={r.key} aria-pressed={active===r.key} onClick={()=>setActive(r.key)}><span>{r.saved?.room.title??'Nova sala'}</span><small>{active===r.key&&r.saved?'Em foco · ':''}{r.status}{r.unread?` · ${r.unread} novas mensagens`:''}</small></button>)}</div><button className="secondary" onClick={add}>+ Outra sala</button></nav><p className="rooms-help">Você ouve apenas a sala em foco. Ao trocar, seu microfone, câmera e compartilhamento são desligados. As outras salas continuam conectadas.</p>{storageError&&<p role="alert" className="rooms-help">{storageError}</p>}<RecordingsPanel r={recordings}/>{rooms.map(r=><RoomWorkspace accountId={accountId} key={r.key} workspaceId={r.key} initial={r.saved} active={r.key===active} onChange={change} onStatus={status} onUnread={unread} onExisting={existing} onRecord={recordings.start} recordingRoom={recordings.recording?.room??null}/>)}</>;
}
function RoomWorkspace({accountId,workspaceId,initial,active,onChange,onStatus,onUnread,onExisting,onRecord,recordingRoom}:{accountId?:string;workspaceId:string;initial:SavedRoom|null;active:boolean;onChange:(key:string,s:SavedRoom|null)=>void;onStatus:(key:string,status:string)=>void;onUnread:(key:string,n:number)=>void;onExisting:(room:string)=>boolean;onRecord:(r:RecordRequest)=>void;recordingRoom:string|null}){
 const [viewQuality,setViewQuality]=useState<Record<string,ScreenQuality>>({});
 const [reportTarget,setReportTarget]=useState<{id:string;name:string}|null>(null);
 const [renameOpen,setRenameOpen]=useState(false),[newTitle,setNewTitle]=useState(''),[recordOpen,setRecordOpen]=useState(false);
 const recordingRef=useRef(recordingRoom);recordingRef.current=recordingRoom;
 const root=useRef<HTMLDivElement>(null),activeRef=useRef(active);activeRef.current=active;
 const saved=useRef(initial),[recovering,setRecovering]=useState(!!initial),[recoveryFailed,setRecoveryFailed]=useState(false);

 const [name,setName]=useState(''),[title,setTitle]=useState('Minha sala'),[mode,setMode]=useState('conversation'),[tab,setTab]=useState('create'),[invite,setInvite]=useState('');
 useEffect(()=>{let cancelled=false;void fetch('/api/account').then(async r=>{if(!r.ok)return;const d:any=await r.json();if(!cancelled&&d.account?.name)setName(n=>n||d.account.name)}).catch(()=>{});return()=>{cancelled=true}},[]);
 const [session,setSession]=useState<Session|null>(null),[members,setMembers]=useState<Member[]>([]),[remote,setRemote]=useState<Record<string,MediaStream>>({}),[states,setStates]=useState<Record<string,string>>({});
 const [screen,setScreen]=useState<MediaStream|null>(null),[busy,setBusy]=useState(false),[mediaBusy,setMediaBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false),[blocked,setBlocked]=useState(false),[installOpen,setInstallOpen]=useState(false),[installEvent,setInstallEvent]=useState<any>(null),[selected,setSelected]=useState<string|null>(null),[connected,setConnected]=useState(true);
 const current=useRef<Session|null>(null),peers=useRef(new Map<string,Peer>()),display=useRef<MediaStream|null>(null),cursor=useRef(0),signalQueue=useRef(new Map<string,Promise<void>>()),repairAttempts=useRef(new Map<string,number>());
 const relayOnly=useRef(false),relayAvailable=useRef(false);
 const iceServers=useRef<RTCIceServer[]>([{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]);
 const [diagnostic,setDiagnostic]=useState(''),[checking,setChecking]=useState(false);
 const [remoteAudio,setRemoteAudio]=useState<Record<string,{stream:MediaStream;kind:'voice'|'screen'}[]>>({});
 const participantPrefs=useParticipantPrefs(session?.room.id??'');
 const [remoteMics,setRemoteMics]=useState<Record<string,MediaStream>>({});
 const [remoteCameras,setRemoteCameras]=useState<Record<string,MediaStream>>({});
 const media=useDevices({onMic:async track=>{await Promise.all([...peers.current.values()].filter(p=>p.pc.signalingState!=='closed').map(p=>p.mic?.sender.replaceTrack(track)))},onCamera:async track=>{await Promise.all([...peers.current.values()].filter(p=>p.pc.signalingState!=='closed').map(p=>p.camera?.sender.replaceTrack(track)))}});
 const {mic,micEnabled,micStream}=media;
 const recordingAudio=useRef<(target:string)=>RecordingAudioSource[]>(()=>[]);recordingAudio.current=(target)=>{if(!activeRef.current||!current.current)return [];const sources:RecordingAudioSource[]=[];const own=micEnabled.current?micStream.current?.getAudioTracks()[0]:null;if(own)sources.push({track:own,gain:1});for(const [id,streams] of Object.entries(remoteAudio))for(const item of streams){if(item.kind==='screen'&&id!==target)continue;for(const track of item.stream.getAudioTracks())sources.push({track,gain:participantVolume(media.prefs.volume,participantPrefs.get(id),item.kind,true)})}if(target===current.current.id)for(const track of display.current?.getAudioTracks()??[])sources.push({track,gain:1});return sources};
 const hosting=session?.id===session?.room.host,canSend=!!session&&(hosting||session.room.mode==='conversation');
 function fail(e:unknown){setError(e instanceof Error?e.message:'Não foi possível concluir. Tente novamente.');}
 function cleanup(){current.current=null;for(const p of peers.current.values())p.pc.close();peers.current.clear();media.stopAll();display.current?.getTracks().forEach(t=>t.stop());display.current=null;cursor.current=0;signalQueue.current.clear();repairAttempts.current.clear();setScreen(null);setRemoteAudio({});setRemoteMics({});setRemote({});setRemoteCameras({});setMembers([]);setStates({});setSelected(null);}
 useEffect(()=>{const params=new URLSearchParams(location.hash.slice(1));const id=params.get('sala');if(id){setInvite(location.href);setTab('join');}if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const fn=(e:Event)=>{e.preventDefault();setInstallEvent(e)};window.addEventListener('beforeinstallprompt',fn);return()=>{window.removeEventListener('beforeinstallprompt',fn);cleanup()}},[]);
 useEffect(()=>{if(!active)return;const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'get_room_status',description:'Consulta o modo e os participantes da sala aberta. Não liga microfone nem captura tela.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Entrada inválida');return {inRoom:!!session,title:session?.room.title??null,mode:session?.room.mode??null,participants:members.map(m=>({name:m.name,microphone:!!m.mic,screen:!!m.screen}))}}} ,{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[session,members,active]);
 function send(target:string,payload:unknown){const s=current.current;if(!s)return Promise.resolve();const task=(signalQueue.current.get(target)??Promise.resolve()).catch(()=>{}).then(async()=>{if(current.current?.id!==s.id)return;for(let attempt=0;attempt<2;attempt++){try{await api({...s,room:s.room.id,action:'signal',target,payload});return}catch(e:any){if(e.status===404)return;if(attempt||[400,401,403,409].includes(e.status))throw e}}});signalQueue.current.set(target,task);return task;}
 async function attachLocal(p:Peer,s:Session){const can=s.room.mode==='conversation'||s.id===s.room.host;await attachChannels(p,{mic:can?micStream.current?.getAudioTracks()[0]:null,video:can?display.current?.getVideoTracks()[0]:null,sound:can?display.current?.getAudioTracks()[0]:null,camera:can&&media.cameraEnabled.current?media.cameraStream.current?.getVideoTracks()[0]:null})}
 function createPeer(m:Member,s:Session){
  const pc=new RTCPeerConnection({iceServers:iceServers.current,iceTransportPolicy:(relayOnly.current||(relayAvailable.current&&(repairAttempts.current.get(m.id)??0)>=2))?'relay':'all'});
  const direction:RTCRtpTransceiverDirection=s.room.mode==='conversation'?'sendrecv':s.id===s.room.host?'sendonly':'recvonly';
  const p:Peer={pc,pending:[],stream:new MediaStream(),created:Date.now()};peers.current.set(m.id,p);
  const offerer=s.id<m.id;
  if(offerer)Object.assign(p,prepareChannels(pc,direction,true));
  pc.onicecandidate=e=>{if(peers.current.get(m.id)!==p)return;if(e.candidate)void send(m.id,{type:'candidate',candidate:e.candidate.toJSON()}).catch(fail)};
  pc.ontrack=e=>{if(peers.current.get(m.id)!==p)return;if(s.room.mode==='presentation'&&m.id!==s.room.host)return;const index=pc.getTransceivers().indexOf(e.transceiver);if(index===3){setRemoteCameras(prev=>({...prev,[m.id]:new MediaStream([e.track])}));return}if(e.track.kind==='audio'){if(index===0)setRemoteMics(prev=>({...prev,[m.id]:new MediaStream([e.track])}));setRemoteAudio(prev=>({...prev,[m.id]:[...(prev[m.id]??[]).filter(item=>item.stream.getTracks()[0].id!==e.track.id),{stream:new MediaStream([e.track]),kind:index===0?'voice':'screen'}]}));return}p.stream=new MediaStream([e.track]);setRemote(prev=>({...prev,[m.id]:p.stream}));};
  pc.onconnectionstatechange=()=>{if(current.current?.id!==s.id||peers.current.get(m.id)!==p)return;if(pc.connectionState==='disconnected')p.disconnectedAt=Date.now();if(pc.connectionState==='connected'){p.disconnectedAt=undefined;}setStates(prev=>({...prev,[m.id]:pc.connectionState}));if(pc.connectionState==='failed')setError('A conexão de áudio e vídeo falhou. Tente reconectar. Clique em Verificar áudio para identificar se a mídia está chegando.');};
  if(offerer)void (async()=>{await attachLocal(p,s);await pc.setLocalDescription(await pc.createOffer());await send(m.id,{type:'offer',sdp:pc.localDescription?.sdp})})().catch(fail);
  return p;
 }
 useEffect(()=>{
  if(!session)return;let stopped=false,timer:ReturnType<typeof setTimeout>;const s=session;current.current=s;
  async function poll(){
   try{const data=await api({...s,room:s.room.id,action:'poll',mic:micEnabled.current,screen:!!display.current,camera:media.cameraEnabled.current,recording:recordingRef.current===s.room.id,cursor:cursor.current});if(stopped)return;setConnected(true);setMembers(data.members);if(data.room&&data.room.title!==s.room.title){const next={...s,room:data.room};setSession(next);if(saved.current){saved.current={...saved.current,room:data.room};onChange(workspaceId,saved.current)}}
    const eligible:Member[]=data.members.filter((m:Member)=>m.id!==s.id&&(s.room.mode==='conversation'||s.id===s.room.host||m.id===s.room.host));
    for(const m of eligible)if(!peers.current.has(m.id))createPeer(m,s);
    for(const [id,p] of peers.current)if(!eligible.some(m=>m.id===id)){p.pc.close();peers.current.delete(id);setStates(prev=>{const next={...prev};delete next[id];return next});setRemoteAudio(prev=>{const next={...prev};delete next[id];return next});setRemoteMics(prev=>{const next={...prev};delete next[id];return next});setRemoteCameras(prev=>{const next={...prev};delete next[id];return next});setRemote(prev=>{const next={...prev};delete next[id];return next});}
    for(const msg of data.signals){if(stopped)return;cursor.current=msg.id;let p=peers.current.get(msg.sender);if(p){const v=JSON.parse(msg.payload);try{if(v.type==='quality'){p.quality=v.quality;if(p.video)await setScreenSenderQuality(p.video.sender,p.quality??'auto',p.limited);continue;}if(v.type==='reset'){p.pc.close();setRemoteAudio(prev=>({...prev,[msg.sender]:[]}));setRemoteMics(prev=>{const next={...prev};delete next[msg.sender];return next});createPeer(eligible.find(m=>m.id===msg.sender)!,s);continue;}if(v.type==='offer'&&p.pc.remoteDescription&&p.pc.remoteDescription.sdp!==v.sdp&&s.id>msg.sender){p.pc.close();setRemoteAudio(prev=>({...prev,[msg.sender]:[]}));setRemoteMics(prev=>{const next={...prev};delete next[msg.sender];return next});p=createPeer(eligible.find(m=>m.id===msg.sender)!,s);}if(v.type==='candidate'){if(p.pc.remoteDescription)await p.pc.addIceCandidate(v.candidate);else p.pending.push(v.candidate)}else{if(v.type==='answer'&&p.pc.signalingState!=='have-local-offer')continue;if(v.type==='offer'&&p.pc.remoteDescription?.sdp===v.sdp)continue;await p.pc.setRemoteDescription({type:v.type,sdp:v.sdp});for(const c of p.pending)await p.pc.addIceCandidate(c);p.pending=[];if(v.type==='offer'){Object.assign(p,prepareChannels(p.pc,s.room.mode==='conversation'?'sendrecv':s.id===s.room.host?'sendonly':'recvonly',false));await attachLocal(p,s);await p.pc.setLocalDescription(await p.pc.createAnswer());await send(msg.sender,{type:'answer',sdp:p.pc.localDescription?.sdp})}}}catch(e){console.error(e);setError('A conexão com um participante falhou. Saia e entre novamente.')}}cursor.current=msg.id;}
   }catch(e:any){if(stopped)return;setConnected(false);if(e.status===401||e.status===403||e.status===404||e.status===409){cleanup();setSession(null);if(e.status!==409){saved.current=null;onChange(workspaceId,null)}else setRecoveryFailed(true);if(e.status===401)location.reload();fail(e);return;}}
   if(!stopped)timer=setTimeout(poll,1500);
  }
  void poll();return()=>{stopped=true;clearTimeout(timer)};
 },[session]);
 useEffect(()=>{if(!session)return;let running=false,stopped=false;const tick=async()=>{if(running)return;running=true;try{for(const p of peers.current.values()){if(stopped)return;if(p.pc.connectionState!=='connected'||!p.video?.sender.track)continue;try{const stats=await p.video.sender.getStats();let constrained=false;stats.forEach(r=>{if(r.type==='outbound-rtp'&&(r.kind==='video'||r.mediaType==='video')&&['cpu','bandwidth'].includes(r.qualityLimitationReason))constrained=true});p.bad=constrained?(p.bad??0)+1:0;p.good=constrained?0:(p.good??0)+1;if(p.bad>=2)p.limited=true;if(p.good>=8)p.limited=false;await setScreenSenderQuality(p.video.sender,p.quality??'auto',p.limited)}catch{}}}finally{running=false}};const timer=setInterval(()=>void tick(),3000);return()=>{stopped=true;clearInterval(timer)}},[session?.id]);
 useEffect(()=>{if(!session)return;let running=false,stopped=false;const timer=setInterval(()=>{if(running)return;running=true;void (async()=>{const s=current.current;if(!s)return;for(const [id,p] of peers.current){if(stopped||s.id>id)continue;const state=p.pc.connectionState,now=Date.now();if(state==='connected'){if(now-(p.created??now)>60000)repairAttempts.current.delete(id);continue}const stalled=state==='failed'||(state==='disconnected'&&now-(p.disconnectedAt??now)>10000)||(['new','connecting'].includes(state)&&now-(p.created??now)>25000);if(!stalled||(repairAttempts.current.get(id)??0)>=3)continue;const member=members.find(m=>m.id===id);if(!member)continue;repairAttempts.current.set(id,(repairAttempts.current.get(id)??0)+1);try{const ice=await api({...s,room:s.room.id,action:'ice'});if(stopped||current.current?.id!==s.id||peers.current.get(id)!==p)return;iceServers.current=ice.iceServers;relayAvailable.current=!!ice.relayConfigured;await send(id,{type:'reset'});if(stopped||peers.current.get(id)!==p)return;p.pc.close();setRemoteAudio(v=>({...v,[id]:[]}));setRemote(v=>{const n={...v};delete n[id];return n});createPeer(member,s)}catch{setError('A conexão de mídia continua instável. Use Reconectar ou Verificar áudio.')}}})().finally(()=>{running=false})},4000);return()=>{stopped=true;clearInterval(timer)}},[session?.id,members.map(m=>m.id).join(',')]);
 async function recover(){
  const old=saved.current;if(!old)return;setRecovering(true);setRecoveryFailed(false);setError('');
  try{const data=await api({...old,room:old.room.id,action:'resume'});const ice=await api({...old,room:old.room.id,action:'ice'});cleanup();iceServers.current=ice.iceServers;relayAvailable.current=!!ice.relayConfigured;const next={...old,room:data.room};current.current=next;setSession(next);setName(old.name);saved.current=next;onChange(workspaceId,next);setConnected(true)}catch(e:any){if(e.status===401||e.status===404){saved.current=null;onChange(workspaceId,null)}else setRecoveryFailed(true);fail(e)}finally{setRecovering(false)}
 }
 useEffect(()=>{if(saved.current)void recover()},[]);
 useEffect(()=>{if(!active){media.setPanel(false);media.stopAll();void stopScreen();void Promise.all([...peers.current.values()].flatMap(p=>[p.mic?.sender.replaceTrack(null),p.camera?.sender.replaceTrack(null)])).catch(fail);setDiagnostic('');setInstallOpen(false);setRenameOpen(false);setRecordOpen(false);setReportTarget(null)}else history.replaceState(null,'',session?`/#sala=${session.room.id}`:'/')},[active,session?.room.id]);
 useEffect(()=>{onStatus(workspaceId,recovering?'Recuperando…':recoveryFailed?'Voltar à sala':session?(connected?'Conectada':'Reconectando…'):'Nova sala')},[recovering,recoveryFailed,session,connected,onStatus,workspaceId]);
 async function enter(create:boolean){setBusy(true);setError('');try{if(!window.RTCPeerConnection)throw new Error('Este navegador não oferece suporte a chamadas. Abra no Chrome ou Edge atualizado.');let room=invite.trim();if(!create){try{const u=new URL(room);room=new URLSearchParams(u.hash.slice(1)).get('sala')||''}catch{}if(!/^[a-f0-9]{32}$/.test(room))throw new Error('Cole o link completo do convite.');if(onExisting(room))return;}
 const data=await api(create?{action:'create',name,title,mode}:{action:'join',name,room});let ice;try{ice=await api({...data,room:data.room.id,action:'ice'})}catch(e){await api({...data,room:data.room.id,action:'leave'}).catch(()=>{});throw e}cleanup();iceServers.current=ice.iceServers;relayAvailable.current=!!ice.relayConfigured;relayOnly.current=false;current.current=data;setSession(data);saved.current={...data,name};onChange(workspaceId,saved.current);setConnected(true);setBlocked(false);
 }catch(e){fail(e)}finally{setBusy(false)}}
 async function toggleMic(){if(activeRef.current&&canSend)await media.toggleMic()}
 async function stopScreen(){const old=display.current;display.current=null;setScreen(null);old?.getTracks().forEach(t=>t.stop());await Promise.all([...peers.current.values()].map(async p=>{await p.video?.sender.replaceTrack(null);await p.sound?.sender.replaceTrack(null)})).catch(fail)}
 async function toggleScreen(){if(!activeRef.current||!canSend||mediaBusy)return;if(display.current){await stopScreen();return}setMediaBusy(true);setError('');try{if(!navigator.mediaDevices?.getDisplayMedia)throw new Error('Este navegador não permite transmitir a tela deste aparelho. No celular você pode assistir à tela enviada pelo computador, conversar e usar a câmera. Capturar a tela do celular exige suporte do sistema, normalmente por um aplicativo nativo.');const stream=await navigator.mediaDevices.getDisplayMedia({video:{width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30,max:30}},audio:true});if(!current.current||!activeRef.current){stream.getTracks().forEach(t=>t.stop());return}const quality=await preferScreenQuality(stream.getVideoTracks()[0]);if(!current.current||!activeRef.current){stream.getTracks().forEach(t=>t.stop());return}if((quality.height??0)<720)setError('A fonte selecionada está abaixo de 720p. Maximize a janela ou compartilhe um monitor de maior resolução.');else if(!stream.getAudioTracks().length)setError('Tela compartilhada sem áudio do sistema. Se disponível, marque Compartilhar áudio na seleção da tela. As vozes da sala ainda podem ser gravadas.');display.current=stream;setScreen(stream);setSelected(session!.id);stream.getVideoTracks()[0].onended=()=>void stopScreen();for(const p of peers.current.values()){await p.video?.sender.replaceTrack(stream.getVideoTracks()[0]);await p.sound?.sender.replaceTrack(stream.getAudioTracks()[0]??null)}}catch(e:any){if(e.name!=='NotAllowedError')fail(e)}finally{setMediaBusy(false)}}
 async function leave(){const s=current.current;if(!s)return;if(s.id===s.room.host&&!window.confirm('Encerrar esta sala para todos? Para apenas alternar, use Minhas salas. Fechar o aplicativo permite voltar enquanto a sala estiver disponível.'))return;setBusy(true);try{await api({...s,room:s.room.id,action:'leave'});cleanup();setSession(null);saved.current=null;onChange(workspaceId,null);setError('')}catch(e){fail(e)}finally{setBusy(false)}}
 async function checkAudio(){setChecking(true);setDiagnostic('Medindo áudio durante 1 segundo…');try{const active=[...peers.current.entries()];const read=async(p:Peer)=>{let sent=0,received=0;const stats=await p.pc.getStats();let relay=false;stats.forEach(r=>{if(r.kind==='audio'&&r.type==='outbound-rtp')sent+=r.bytesSent??0;if(r.kind==='audio'&&r.type==='inbound-rtp')received+=r.bytesReceived??0;if(r.type==='transport'&&r.selectedCandidatePairId){const pair=stats.get(r.selectedCandidatePairId);relay=stats.get(pair?.localCandidateId)?.candidateType==='relay'||stats.get(pair?.remoteCandidateId)?.candidateType==='relay'}});return {sent,received,relay}};const before=await Promise.all(active.map(([,p])=>read(p)));await new Promise(r=>setTimeout(r,1000));const lines=await Promise.all(active.map(async([id,p],i)=>{const after=await read(p);const who=members.find(m=>m.id===id)?.name??'Participante';return `${who}: conexão ${p.pc.connectionState}; áudio enviado ${Math.max(0,after.sent-before[i].sent)} bytes/s; recebido ${Math.max(0,after.received-before[i].received)} bytes/s; caminho ${after.relay?'servidor TURN':'direto ou ainda indisponível'}.`}));const track=micStream.current?.getAudioTracks()[0];setDiagnostic([`Modo: ${session?.room.mode==='presentation'?'apresentação (plateia não fala)':'conversa em grupo'}.`,`Servidor de retransmissão: ${relayAvailable.current?'configurado':'indisponível nesta sessão'}.`, `Microfone: ${micEnabled.current?'ligado':'desligado'}; faixa ${track?.readyState??'não aberta'}; saída ${media.prefs.volume}%.`,...lines,...(!active.length?['Ainda não há outro participante conectado.']:[]),'Se recebe bytes e não ouve: clique em Ouvir sala, confira a saída e o volume. Se a conexão falhar ou o envio permanecer zerado com microfone ligado: tente Reconectar.'].join('\n'))}catch{setDiagnostic('A conexão mudou durante a verificação. Tente novamente.')}finally{setChecking(false)}}
 async function reconnect(forceRelay=false){const s=current.current;if(!s)return;try{const ice=await api({...s,room:s.room.id,action:'ice'});iceServers.current=ice.iceServers;relayAvailable.current=!!ice.relayConfigured;if(forceRelay&&!ice.relayConfigured)throw new Error('O servidor de retransmissão não está disponível.');relayOnly.current=forceRelay}catch(e){fail(e);return}await Promise.all([...peers.current.keys()].map(id=>send(id,{type:'reset'}))).catch(fail);for(const p of peers.current.values())p.pc.close();peers.current.clear();setRemote({});setRemoteAudio({});setRemoteMics({});setRemoteCameras({});setStates({});setError('');setSession({...s})}
 async function rename(){if(!session)return;setBusy(true);try{await api({...session,room:session.room.id,action:'rename',title:newTitle});setRenameOpen(false);setError('')}catch(e){fail(e)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(`${location.origin}/#sala=${session!.room.id}`);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('Não foi possível copiar. Copie o endereço desta página.')}}
 async function install(){if(installEvent){await installEvent.prompt();setInstallEvent(null)}else setInstallOpen(true)}
 const people=members.map(m=>m.id===session?.id?{...m,mic:mic?1:0,screen:screen?1:0,camera:media.cameraLive?1:0}:m);
 const shares=people.filter(m=>m.screen);const focus=shares.find(m=>m.id===selected)??shares[0];
 const focusStream=focus?.id===session?.id?screen:focus?remote[focus.id]:null;
 useEffect(()=>{if(focus&&session&&focus.id!==session.id&&states[focus.id]==='connected')void send(focus.id,{type:'quality',quality:viewQuality[focus.id]??'auto'}).catch(fail)},[focus?.id,session?.id,viewQuality,states]);
 return <div ref={root} className="app-shell" hidden={!active}>
  <header className="topbar"><a className="brand" href="/" onClick={e=>{if(session)e.preventDefault()}} aria-label="Sala, início"><span className="brand-icon"><AudioLines size={25}/></span><span>sala<span className="brand-period">.</span></span></a><span className="top-caption">VOZ & TELA</span><a className="settings-button" href="/conta" target="_blank" rel="noopener noreferrer">{accountId?'Minha conta':'Entrar (opcional)'}</a>{accountId&&<a className="settings-button" href="/signout-with-chatgpt?return_to=%2F" target="_top">Sair da conta</a>}<button className="settings-button" onClick={()=>media.setPanel(true)}><Settings2 size={17}/><span>Configurações</span></button><ProgramSettings/><button className="install-button" onClick={install}><Download size={16}/><span>Instalar aplicativo</span></button></header>
  {(recovering||recoveryFailed)&&<div className="recovery-banner" role="status">{recovering?'Recuperando sua participação na sala…':'Não foi possível recuperar a sala.'}{recoveryFailed&&<><button className="secondary" onClick={()=>void recover()}>Tentar voltar</button><button className="secondary" onClick={()=>{saved.current=null;setRecoveryFailed(false);onChange(workspaceId,null)}}>Remover da lista</button></>}</div>}<main className={session?'in-room':'lobby'}>
   {!session?<><section className="welcome"><span className="eyebrow">UM LUGAR PARA SE CONECTAR</span><h1>Uma sala.<br/>Sua voz.<br/><span>Todo mundo junto.</span></h1><p>Abra uma conversa ou apresente sua tela.<br/>Convide as pessoas e deixe o papo acontecer.</p><div className="welcome-foot"><Headphones size={21}/><span>Use fones para conversar sem eco.</span></div><div className="feature-line"><span><Mic size={16}/> Áudio ao vivo</span><span><MonitorUp size={16}/> Tela compartilhada</span></div></section>
   <section className="entry-card"><div className="entry-heading"><span className="small-icon"><Radio size={22}/></span><div><h2>Vamos nos encontrar?</h2><p>Sua próxima conversa começa aqui.</p></div></div>
   <Tabs value={tab} onValueChange={setTab}><TabsList className="entry-tabs"><TabsTrigger value="create">Criar uma sala</TabsTrigger><TabsTrigger value="join">Entrar com convite</TabsTrigger></TabsList>
   <label className="field">Seu nome<input value={name} onChange={e=>setName(e.target.value)} maxLength={40} placeholder="Como você quer aparecer?" autoComplete="nickname"/></label>
   <TabsContent value="create"><form onSubmit={e=>{e.preventDefault();void enter(true)}}><label className="field">Nome da sala<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={70} required placeholder="Ex.: Conversa da equipe"/></label>
    <label className="field-label">Como vai ser?</label><RadioGroup value={mode} onValueChange={setMode} className="mode-group"><label className={'mode-option '+(mode==='conversation'?'active':'')}><Users size={22}/><span><strong>Conversa em grupo</strong><small>Todos podem falar e mostrar a tela.</small></span><RadioGroupItem value="conversation" aria-label="Conversa em grupo"/></label><label className={'mode-option '+(mode==='presentation'?'active':'')}><Presentation size={22}/><span><strong>Apresentação</strong><small>Você transmite. A plateia acompanha.</small></span><RadioGroupItem value="presentation" aria-label="Apresentação"/></label></RadioGroup>
    <button className="primary wide" disabled={busy||recovering||recoveryFailed||!name.trim()||!title.trim()}>{busy?'Abrindo sala…':'Criar sala'}<ArrowUpRight size={19}/></button></form></TabsContent>
   <TabsContent value="join"><form onSubmit={e=>{e.preventDefault();void enter(false)}}><label className="field">Link do convite<input value={invite} onChange={e=>setInvite(e.target.value)} placeholder="Cole aqui o link da sala" required/></label><p className="join-note">Você entra com o microfone desligado. Ative quando estiver pronto para falar.</p><button className="primary wide" disabled={busy||recovering||recoveryFailed||!name.trim()||!invite.trim()}>{busy?'Entrando…':'Entrar na sala'}<ArrowUpRight size={19}/></button></form></TabsContent></Tabs><div className="card-footer"><ShieldCheck size={15}/><span>Gravação local opcional · Até 15 pessoas por sala</span></div></section></>:<>
    <div className="room-heading"><div><span className="eyebrow">{hosting?'SUA SALA':session.room.mode==='presentation'?'VOCÊ ESTÁ NA PLATEIA':'SALA DE CONVERSA'}</span><div className="room-title-edit"><h1>{session.room.title}</h1>{hosting&&<button className="icon-button" aria-label="Renomear sala" onClick={()=>{setNewTitle(session.room.title);setRenameOpen(true)}}><Pencil size={19}/></button>}</div></div><div className="room-info"><span className="mode-badge">{session.room.mode==='conversation'?<Users size={16}/>:<Presentation size={16}/>} {session.room.mode==='conversation'?'Conversa':'Apresentação'}</span><button className="secondary" onClick={copy}>{copied?<Check size={17}/>:<LinkIcon size={17}/>} {copied?'Link copiado':'Convidar'}</button></div></div>
    <div className="room-layout"><section className="stage"><div className="stage-top"><span>{focus?`${focus.name} está compartilhando · ${screenQualityLabel(focusStream?.getVideoTracks()[0])}`:'Tela compartilhada'}</span>{focus&&focus.id!==session.id&&<label className="quality-control">Qualidade<select aria-label="Qualidade da tela assistida" value={viewQuality[focus.id]??'auto'} onChange={e=>setViewQuality(old=>({...old,[focus.id]:e.target.value as ScreenQuality}))}><option value="auto">Automático · 1080p / 720p</option><option value="1080">1080p</option><option value="720">720p · economizar dados</option></select></label>}{focus&&<button className="secondary record-start" disabled={!focusStream||!!recordingRoom} onClick={()=>setRecordOpen(true)}><Video size={16}/> Gravar tela</button>}{focus&&<button aria-label="Ver tela em tamanho máximo" className="icon-button" onClick={()=>root.current?.querySelector('.stage')?.requestFullscreen().catch(fail)}><Maximize2 size={18}/></button>}</div><div className="stage-content">{focusStream?<video className="main-screen" autoPlay muted playsInline ref={el=>{if(el&&el.srcObject!==focusStream){el.srcObject=focusStream;void el.play().catch(()=>{})}}}/>:<div className="stage-empty"><span className="stage-symbol"><MonitorUp size={38} strokeWidth={1.3}/></span><h2>{canSend?'Sua tela também faz parte da conversa.':'A apresentação vai começar.'}</h2><p>{canSend?'Compartilhe uma janela, uma aba ou a tela inteira.':'Aguarde o anfitrião ligar o microfone ou compartilhar a tela.'}</p>{canSend&&<button className="secondary" onClick={toggleScreen} disabled={mediaBusy}><MonitorUp size={17}/> Compartilhar tela</button>}</div>}</div><div className="stage-bottom"><span><Users size={15}/> {people.length} de 15 pessoas</span><span>{!connected?'Reconectando à sala…':Object.values(states).some(v=>v==='failed')?'Falha no áudio/vídeo':Object.values(states).some(v=>v==='connected')?'Mídia conectada':people.length>1?'Conectando áudio e vídeo…':'Aguardando companhia'}</span></div></section>
    <aside className="people-panel"><div className="panel-title"><h2>Na sala</h2><span>{people.length}</span></div><div className="people-list">{people.map((m,i)=>{const content=<><span className={'avatar color-'+i%4}>{initials(m.name)}</span><span className="person-label"><strong>{m.name}{m.id===session.id?' (você)':''}</strong>{(m.id===session.id?recordingRoom===session.room.id:!!m.recording)&&<span className="recording-badge">● Gravando uma tela</span>}<small>{m.id===session.id?(hosting?'Anfitrião · você':'Você'):session.room.mode==='presentation'&&m.id!==session.room.host&&!hosting?'Plateia':states[m.id]==='connected'?'Áudio/vídeo conectado':states[m.id]==='failed'?'Falha no áudio/vídeo':states[m.id]==='disconnected'?'Mídia interrompida':'Conectando mídia…'}</small></span><MicIndicator name={m.name} enabled={!!m.mic} stream={m.id===session.id?micStream.current:states[m.id]==='connected'?remoteMics[m.id]??null:null}/></>;return m.id===session.id?<SelfOptions key={m.id} name={m.name} active={active} canSend={canSend} mic={mic} camera={media.cameraLive} screen={!!screen} busy={media.busy} screenBusy={mediaBusy} onMic={()=>void toggleMic()} onCamera={()=>void media.toggleCamera()} onScreen={()=>void toggleScreen()} onSettings={()=>media.setPanel(true)}>{content}</SelfOptions>:<ParticipantOptions key={m.id} name={m.name} prefs={participantPrefs.get(m.id)} onChange={patch=>participantPrefs.update(m.id,patch)} sharing={!!m.screen} active={active} error={participantPrefs.error} onReport={()=>setReportTarget(m)} onWatch={()=>{setSelected(m.id);root.current?.querySelector('.stage')?.scrollIntoView({behavior:'smooth',block:'start'})}}>{content}</ParticipantOptions>})}</div>{shares.length>0&&<div className="share-list"><h3>Telas disponíveis</h3>{shares.map(m=><button key={m.id} className={focus?.id===m.id?'chosen':''} onClick={()=>setSelected(m.id)}><MonitorUp size={16}/><span>{m.name}</span></button>)}</div>}<div className="invite-note"><LinkIcon size={20}/><p>A conversa fica melhor com companhia.</p><button onClick={copy}>{copied?'Copiado!':'Copiar convite'} <ArrowUpRight size={15}/></button></div><RoomChat key={session.room.id+session.id} session={session} active={active} onUnread={n=>onUnread(workspaceId,n)}/></aside></div>
    <div className="camera-strip">{people.filter(m=>m.camera&&(m.id===session.id||!participantPrefs.get(m.id).hideCamera)).map(m=>{const stream=m.id===session.id?media.camera:remoteCameras[m.id];return stream?<div className="camera-tile" key={m.id}><CameraView stream={stream} mirror={m.id===session.id&&media.prefs.mirror}/><span>{m.name}{m.id===session.id?" (você)":""}</span></div>:null})}</div><div className="media-elements">{Object.entries(remoteAudio).flatMap(([id,streams])=>streams.map(({stream,kind})=><Media key={id+stream.id} stream={stream} output={media.prefs.output} volume={participantVolume(media.prefs.volume,participantPrefs.get(id),kind,active)} onBlocked={()=>setBlocked(true)} onError={e=>media.setError(mediaError(e))}/>))}</div>
    {session&&<button className="audio-unlock" onClick={()=>{Promise.all([...root.current!.querySelectorAll<HTMLMediaElement>('audio,video')].map(v=>v.play())).then(()=>setBlocked(false)).catch(()=>setError('Clique novamente para liberar o áudio.'))}}><Volume2 size={18}/> {blocked?'Clique para liberar o áudio':'Ouvir sala'}</button>}
    <div className="controls"><div className="control-hint"><Headphones size={18}/><span>{canSend?'Seu espaço de conversa':'Você está na plateia: só pode ouvir'}</span></div><div className="control-buttons"><button className="control" onClick={checkAudio} disabled={checking}><Headphones size={21}/><span>Verificar áudio</span></button><button className="control" onClick={()=>void reconnect()}><Radio size={21}/><span>Reconectar</span></button>{canSend&&<><button className={(active?'control ':'background-control ')+(mic?'enabled':'')} onClick={toggleMic} disabled={media.busy} aria-pressed={mic}>{mic?<Mic size={21}/>:<MicOff size={21}/>}<span>{mic?'Silenciar':'Ligar microfone'}</span></button><button className={(active?'control ':'background-control ')+(media.cameraLive?'enabled':'')} onClick={media.toggleCamera} disabled={media.busy} aria-pressed={media.cameraLive}>{media.cameraLive?<CameraOff size={21}/>:<Camera size={21}/>}<span>{media.cameraLive?'Desligar câmera':'Ligar câmera'}</span></button><button className={(active?'control ':'background-control ')+(screen?'enabled':'')} onClick={toggleScreen} disabled={mediaBusy} aria-pressed={!!screen}>{screen?<MonitorOff size={21}/>:<MonitorUp size={21}/>}<span>{screen?'Parar tela':'Compartilhar'}</span></button></>}<button className="control leave" disabled={busy} onClick={leave}><LogOut size={21}/><span>{hosting?'Encerrar sala':'Sair da sala'}</span></button></div></div>
   </>}
   {media.error&&!media.open&&<div className="error" role="alert"><span>{media.error}</span><button onClick={()=>media.setError('')} aria-label="Fechar aviso">×</button></div>}{error&&<div className="error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Fechar aviso">×</button></div>}
  </main><footer className="site-footer"><span>SALA · VOZ & TELA</span><span>{session?'Salas expiram após 12 horas.':'No navegador ou instalado no seu computador.'}</span><a href="/termos" target="_blank" rel="noopener noreferrer">Termos e privacidade · minuta</a></footer>
  <Dialog open={renameOpen} onOpenChange={setRenameOpen}><DialogContent><DialogHeader><DialogTitle>Renomear sala</DialogTitle><DialogDescription>O novo nome aparece para todos. O link do convite continua o mesmo.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void rename()}}><label className="field">Nome da sala<input value={newTitle} onChange={e=>setNewTitle(e.target.value)} maxLength={70} required/></label><button className="primary" disabled={busy||!newTitle.trim()}>Salvar nome</button></form></DialogContent></Dialog>
  <Dialog open={recordOpen} onOpenChange={setRecordOpen}><DialogContent><DialogHeader><DialogTitle>Gravar a tela de {focus?.name}</DialogTitle><DialogDescription>Grava a tela selecionada e o áudio do compartilhamento, quando transmitido. Inclui as vozes disponíveis da sala e seu microfone quando ligado, respeitando os volumes locais. As câmeras não entram no vídeo. Prioriza 1080p; quando indisponível, usa a resolução recebida, preferencialmente 720p.</DialogDescription></DialogHeader><p>Avise os participantes. Seu nome será marcado como “Gravando uma tela”. Ao parar, baixe o VOD em Gravações. O vídeo não é enviado ao servidor.</p><button className="primary" disabled={!focusStream||!!recordingRoom} onClick={()=>{const video=focusStream?.getVideoTracks()[0];if(!session||!focus||!video)return;const audio=focus.id===session.id?screen?.getAudioTracks()[0]:remoteAudio[focus.id]?.find(item=>item.kind==='screen')?.stream.getAudioTracks()[0];onRecord({room:session.room.id,roomTitle:session.room.title,person:focus.name,video,audio,audioSources:()=>recordingAudio.current(focus.id)});setRecordOpen(false)}}>Iniciar gravação</button></DialogContent></Dialog>
  {session&&<ReportParticipant session={session} target={reportTarget} onClose={()=>setReportTarget(null)}/>}<Settings m={media}/><Dialog open={!!diagnostic} onOpenChange={open=>{if(!open)setDiagnostic('')}}><DialogContent><DialogHeader><DialogTitle>Verificação de áudio</DialogTitle><DialogDescription>Fale enquanto mede. Os números indicam tráfego de áudio, não garantem voz audível.</DialogDescription></DialogHeader><pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit',fontSize:14}}>{diagnostic}</pre><button className="secondary" onClick={()=>{setDiagnostic('');void reconnect(true)}}>Reconectar pelo servidor</button></DialogContent></Dialog><Dialog open={installOpen} onOpenChange={setInstallOpen}><DialogContent className="install-dialog"><DialogHeader><DialogTitle>Instalar no Windows</DialogTitle><DialogDescription>Escolha o aplicativo para Windows ou a instalação pelo navegador.</DialogDescription></DialogHeader><a className="primary" href="https://github.com/glauberschmit-ctrl/sala-voz-tela/releases/download/v0.1.4/Sala-Web-Setup-0.1.4.exe">Baixar instalador Windows 0.1.4</a><p>O aplicativo para Windows oferece bandeja e a opção de escolher o comportamento do X em Programa.</p><ol><li>No menu do navegador, procure <strong>Aplicativos → Instalar este site como aplicativo</strong> (Edge) ou a opção <strong>Instalar Sala</strong> (Chrome).</li><li>Confirme a instalação. O Sala abrirá em uma janela própria, com atalho no Windows.</li></ol><p>Esta é uma instalação pelo navegador. Você precisa de internet para participar das salas.</p></DialogContent></Dialog>
 </div>
}
