'use client';
import {useState,useEffect} from 'react';
import {ShieldCheck,Mail,Eye,EyeOff} from 'lucide-react';
import {GoogleAuthProvider,signInWithPopup,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,sendEmailVerification,updateProfile} from 'firebase/auth';
import {firebaseAuth,syncSession,authError,setAuthFlowBusy} from '../firebase-client';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
export default function Access({onGuest}:{onGuest?:()=>void}){
 const [tab,setTab]=useState('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[consent,setConsent]=useState(false),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reset,setReset]=useState(false),[desktop,setDesktop]=useState(false);
 useEffect(()=>setDesktop(/Electron\//.test(navigator.userAgent)),[]);
 function changeTab(value:string){setTab(value);setReset(false);setError('');setMessage('');setPassword('');setConfirm('')}
 async function authenticate(google=false){setError('');setMessage('');if(tab==='signup'&&!google&&!consent&&!reset){setError('Leia e aceite os termos para criar sua conta.');return}if(!google&&!reset&&tab==='signup'&&(password.length<12||password!==confirm||!name.trim())){setError(password!==confirm?'As senhas não coincidem.':'Informe seu nome e use uma senha com pelo menos 12 caracteres.');return}setBusy(true);setAuthFlowBusy(true);try{const auth=firebaseAuth();if(reset){try{await sendPasswordResetEmail(auth,email.trim())}catch(e){if((e as {code?:string}).code!=='auth/user-not-found')throw e}setMessage('Se houver uma conta para esse e-mail, você receberá instruções de recuperação. Confira também o spam.');return}let user;if(google){const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});user=(await signInWithPopup(auth,provider)).user}else if(tab==='signup'){user=(await createUserWithEmailAndPassword(auth,email.trim(),password)).user;await updateProfile(user,{displayName:name.trim()});await user.getIdToken(true);try{await sendEmailVerification(user)}catch{/* The profile offers a resend action. */}}else{user=(await signInWithEmailAndPassword(auth,email.trim(),password)).user}await syncSession(user);setPassword('');setConfirm('');location.assign('/conta')}catch(e){setError(authError(e))}finally{setBusy(false);setAuthFlowBusy(false)}}
 return <><Tabs value={tab} onValueChange={changeTab}><TabsList className="access-tabs"><TabsTrigger value="login" disabled={busy}>Entrar</TabsTrigger><TabsTrigger value="signup" disabled={busy}>Criar conta</TabsTrigger></TabsList><TabsContent value="login"><h2>{reset?'Recupere seu acesso.':'Bom ter você por aqui.'}</h2><p className="access-subtitle">{reset?'Enviaremos um link para você definir uma nova senha.':'Entre com Google ou com seu e-mail e senha.'}</p></TabsContent><TabsContent value="signup"><h2>Crie sua conta no Sala.</h2><p className="access-subtitle">Escolha seu nome e tenha um perfil para suas conversas.</p></TabsContent></Tabs>
 {!reset&&<><button className="provider-button google-login" type="button" disabled={busy||desktop} onClick={()=>void authenticate(true)}><b aria-hidden="true" style={{fontSize:20,width:20,fontFamily:'Arial, sans-serif'}}>G</b><span>{busy?'Aguarde…':'Continuar com Google'}</span></button>{desktop&&<p className="provider-note">O Google requer o navegador. Neste aplicativo, use e-mail e senha.</p>}<p className="provider-note">Ao continuar com Google, você concorda com os <a href="/termos">termos de uso e privacidade</a>.</p><div className="access-divider"><span><Mail size={14}/> ou com seu e-mail</span></div></>}
 <form className="email-access-form" onSubmit={e=>{e.preventDefault();void authenticate()}}><fieldset disabled={busy}><legend className="sr-only">{reset?'Recuperar senha':tab==='signup'?'Dados para criar conta':'Dados de acesso'}</legend>
 {tab==='signup'&&<label className="field">Nome de exibição<input type="text" name="displayName" autoComplete="nickname" maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="Como você quer aparecer?" required/><small>É o nome que as outras pessoas verão nas salas.</small></label>}
 <label className="field">E-mail<input type="email" name="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@exemplo.com" required/></label>
 {!reset&&<><label className="field">Senha<span className="password-field"><input type={show?'text':'password'} name="password" autoComplete={tab==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder={tab==='signup'?'Crie uma senha':'Sua senha'} minLength={tab==='signup'?12:undefined} required/><button type="button" aria-label={show?'Ocultar senha':'Mostrar senha'} aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span>{tab==='signup'&&<small>Use pelo menos 12 caracteres.</small>}</label>
 {tab==='signup'?<><label className="field">Confirmar senha<input type={show?'text':'password'} name="confirmPassword" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repita sua senha" required/></label><label className="account-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>Li e aceito os <a href="/termos">termos de uso e privacidade</a>.</span></label></>:<button type="button" className="account-forgot" onClick={()=>{setReset(true);setError('');setMessage('');setPassword('')}}>Esqueci minha senha</button>}</>}
 {error&&<p className="access-message auth-error" role="alert">{error} <a href="/conta" target="_blank" rel="noopener noreferrer">Abrir em nova aba</a></p>}{message&&<p className="access-message" role="status">{message}</p>}
 <button className="primary wide" type="submit">{busy?'Aguarde…':reset?'Enviar link de recuperação':tab==='signup'?'Criar minha conta':'Entrar'}</button>
 {reset&&<button type="button" className="guest-access wide" onClick={()=>{setReset(false);setError('');setMessage('')}}>Voltar para entrar</button>}
 </fieldset></form>
 <div className="access-divider"><span>login é opcional</span></div><a className="guest-access" href="/" onClick={e=>{if(onGuest){e.preventDefault();onGuest()}}}>Continuar sem conta</a><p className="access-security"><ShieldCheck size={15}/> Sua senha é gerenciada pelo Firebase.</p></>;
}
