import {env} from 'cloudflare:workers';
import {db} from './raw';
export function operationalConfig(){const e=env as unknown as Record<string,string|undefined>;return {admins:(e.SALA_ADMIN_EMAILS||'').split(',').map(s=>s.trim().toLowerCase()).filter(Boolean),moderationKey:e.SALA_MODERATION_API_KEY||'',moderationRequired:e.SALA_MODERATION_REQUIRED==='true',contact:e.SALA_PRIVACY_EMAIL||''}}
export async function audit(event:string,actor:string|null,room:string|null,status:number,detail=''){
 await db().prepare('INSERT INTO audit_events(created,event,actor,room,status,detail) VALUES(?,?,?,?,?,?)').bind(Date.now(),event.slice(0,80),actor,room,status,detail.slice(0,1500)).run();
}
export async function limited(key:string,max:number,seconds:number){const now=Date.now(),bucket=Math.floor(now/(seconds*1000));const r=await db().prepare('INSERT INTO rate_limits(key,expires,count) VALUES(?,?,1) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key+':'+bucket,(bucket+1)*seconds*1000).first<{count:number}>();return (r?.count??max+1)>max}
export async function requestLimit(req:Request,action:string){const ip=req.headers.get('cf-connecting-ip')||'unknown';const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ip));const hash=Array.from(new Uint8Array(bytes),v=>v.toString(16).padStart(2,'0')).join('');return limited('entry:'+hash+':'+action,action==='create'?10:30,60)}
export async function observe(req:Request,handler:(r:Request)=>Promise<Response>,route:string){const started=Date.now();const response=await handler(req);try{const size=response.headers.get('content-length');const bytes=size?Number(size):new TextEncoder().encode(await response.clone().text()).byteLength;const minute=Math.floor(Date.now()/60000)*60000;await db().prepare('INSERT INTO operational_counters(key,minute,route,requests,errors,bytes_out,duration_ms) VALUES(?,?,?,1,?,?,?) ON CONFLICT(key) DO UPDATE SET requests=requests+1,errors=errors+excluded.errors,bytes_out=bytes_out+excluded.bytes_out,duration_ms=duration_ms+excluded.duration_ms').bind(route+':'+minute,minute,route,response.status>=400?1:0,Number.isFinite(bytes)?bytes:0,Date.now()-started).run()}catch{console.error('operational-metrics-write-failed')}return response}
export async function retention(){const now=Date.now();await db().batch([db().prepare('DELETE FROM audit_events WHERE created<?').bind(now-30*86400000),db().prepare('DELETE FROM operational_counters WHERE minute<?').bind(now-30*86400000),db().prepare('DELETE FROM rate_limits WHERE expires<?').bind(now),db().prepare("DELETE FROM reports WHERE status<>'open' AND created<?").bind(now-90*86400000)])}
export async function moderateText(text:string,actor:string,room:string){const config=operationalConfig();if(!config.moderationKey){if(config.moderationRequired)throw Object.assign(new Error('Envio temporariamente indisponível: moderação não configurada.'),{status:503});return}
 if(await limited('moderation:'+actor,30,60))throw Object.assign(new Error('Muitos envios para análise. Aguarde um minuto.'),{status:429});
 try{const response=await fetch('https://api.openai.com/v1/moderations',{method:'POST',headers:{Authorization:'Bearer '+config.moderationKey,'Content-Type':'application/json'},body:JSON.stringify({model:'omni-moderation-latest',input:text}),signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error('provider');const result:any=await response.json();if(!Array.isArray(result.results)||typeof result.results[0]?.flagged!=='boolean')throw new Error('invalid-response');if(result.results.some((r:any)=>r.flagged)){const categories=Object.keys(result.results[0].categories||{}).filter(k=>result.results[0].categories[k]===true).join(',');await audit('moderation.text.blocked',actor,room,422,categories);throw Object.assign(new Error('Mensagem retida pela política de segurança. Você pode solicitar revisão pelo canal de suporte.'),{status:422})}}catch(e:any){if(e.status===422)throw e;await audit('moderation.unavailable',actor,room,503);throw Object.assign(new Error('A moderação está indisponível. Tente novamente; a mensagem não foi enviada.'),{status:503})}
}
