export type AudioPrefs={input:string;output:string;camera:string;gain:number;volume:number;monitorVolume:number;echo:boolean;noise:boolean;gate:boolean;gateThreshold:number;autoGain:boolean;resolution:string;mirror:boolean};
export const defaults:AudioPrefs={input:'default',output:'default',camera:'default',gain:100,volume:80,monitorVolume:35,echo:true,noise:true,gate:true,gateThreshold:-50,autoGain:false,resolution:'720',mirror:true};
export function normalizePrefs(raw:Partial<AudioPrefs>):AudioPrefs {const p={...defaults};for(const key of ['input','output','camera'] as const)if(typeof raw[key]==='string'&&raw[key])p[key]=raw[key];for(const key of ['gain','volume','monitorVolume'] as const)if(typeof raw[key]==='number'&&Number.isFinite(raw[key]))p[key]=Math.max(0,Math.min(key==='gain'?200:100,raw[key]));for(const key of ['echo','noise','gate','autoGain','mirror'] as const)if(typeof raw[key]==='boolean')p[key]=raw[key];if(typeof raw.gateThreshold==='number'&&Number.isFinite(raw.gateThreshold))p.gateThreshold=Math.max(-70,Math.min(-25,raw.gateThreshold));if(['480','720','1080'].includes(raw.resolution??''))p.resolution=raw.resolution!;return p;}
export async function routeAudio(el:HTMLMediaElement,output:string,volume:number){el.volume=Math.max(0,Math.min(1,volume/100));const sink=output==='default'?'':output;if(typeof el.setSinkId==='function')await el.setSinkId(sink);else if(sink)throw new Error('Este navegador usa a saída de áudio padrão do sistema.');}
export class MicPipeline {
 raw:MediaStream;context:AudioContext;gain:GainNode;analyser:AnalyserNode;out:MediaStream;monitor:MediaStream;gateNode:AudioWorkletNode|null=null;filterNotice='';
 constructor(raw:MediaStream,context:AudioContext,level:number,processor?:AudioWorkletNode,noise=false){this.raw=raw;this.context=context;const source=context.createMediaStreamSource(raw);this.gain=context.createGain();this.gain.gain.value=level/100;this.analyser=context.createAnalyser();this.analyser.fftSize=1024;const out=context.createMediaStreamDestination(),monitor=context.createMediaStreamDestination();let last:AudioNode=source;if(noise){const highpass=context.createBiquadFilter();highpass.type='highpass';highpass.frequency.value=85;highpass.Q.value=.707;last.connect(highpass);last=highpass}if(processor){last.connect(processor);last=processor;this.gateNode=processor}last.connect(this.gain);this.gain.connect(this.analyser);this.gain.connect(out);this.gain.connect(monitor);this.out=out.stream;this.monitor=monitor.stream;this.out.getAudioTracks().forEach(t=>t.enabled=false);}
 setGain(value:number){this.gain.gain.value=Math.max(0,Math.min(2,value/100))}
 setGate(enabled:boolean,threshold:number){this.gateNode?.parameters.get('enabled')?.setValueAtTime(enabled?1:0,this.context.currentTime);this.gateNode?.parameters.get('threshold')?.setValueAtTime(Math.max(-70,Math.min(-25,threshold)),this.context.currentTime)}
 setEnabled(enabled:boolean){this.out.getAudioTracks().forEach(t=>t.enabled=enabled)}
 dispose(){this.gateNode?.port.postMessage('stop');this.gateNode?.disconnect();[this.raw,this.out,this.monitor].forEach(s=>s.getTracks().forEach(t=>t.stop()));void this.context.close().catch(()=>{})}
}
export async function acquireMic(p:AudioPrefs){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Abra no Chrome ou Edge usando o endereço HTTPS do aplicativo para acessar o microfone.');const context=new AudioContext();try{await context.resume();const raw=await navigator.mediaDevices.getUserMedia({audio:{deviceId:p.input==='default'?undefined:{exact:p.input},echoCancellation:p.echo,noiseSuppression:p.noise,autoGainControl:p.autoGain,channelCount:1}});try{let processor:AudioWorkletNode|undefined;let notice='';try{if(!context.audioWorklet)throw new Error('unsupported');await context.audioWorklet.addModule('/noise-gate.js');processor=new AudioWorkletNode(context,'sala-noise-gate',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[1],parameterData:{enabled:p.gate?1:0,threshold:p.gateThreshold}})}catch{notice='O filtro de pausas não está disponível neste navegador. A redução de ruído do navegador continua conforme o suporte.'}const pipeline=new MicPipeline(raw,context,p.gain,processor,p.noise);pipeline.filterNotice=notice;return pipeline}catch(e){raw.getTracks().forEach(t=>t.stop());throw e}}catch(e){void context.close().catch(()=>{});throw e}}
export function mediaError(e:unknown){const err=e as DOMException;if(err.name==='NotAllowedError')return 'Acesso não permitido. Libere o dispositivo nas permissões do navegador e tente novamente.';if(err.name==='NotFoundError'||err.name==='OverconstrainedError')return 'Dispositivo indisponível. Selecione outro ou use Padrão do sistema.';if(err.name==='NotReadableError')return 'Não foi possível abrir o dispositivo. Verifique se outro aplicativo está usando ele.';return err.message||'Não foi possível acessar o dispositivo.'}
