'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,X} from 'lucide-react';
export type GifItem={id:string;title:string;url:string};
export default function GifPicker({auth,onChoose,onClose}:{auth:{room:string;id:string;token:string};onChoose:(item:GifItem)=>void;onClose:()=>void}){
 const [query,setQuery]=useState(''),[items,setItems]=useState<GifItem[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[choosing,setChoosing]=useState(false);
 const controller=useRef<AbortController|null>(null),sequence=useRef(0),cache=useRef(new Map<string,GifItem[]>());
 useEffect(()=>{void search('');return()=>{sequence.current++;controller.current?.abort()}},[]);
 async function call(body:Record<string,unknown>,signal:AbortSignal){return fetch('/api/gifs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...auth,...body}),signal:AbortSignal.any([signal,AbortSignal.timeout(20000)])})}
 async function search(q:string){controller.current?.abort();const c=new AbortController();controller.current=c;const n=++sequence.current;setError('');const saved=cache.current.get(q);if(saved){setItems(saved);setLoading(false);return}setLoading(true);setItems([]);try{const r=await call({action:'search',q},c.signal);const d=await r.json() as {error?:string;items:GifItem[]};if(!r.ok)throw new Error(d.error);if(n!==sequence.current)return;setItems(d.items);if(cache.current.size>=20)cache.current.clear();cache.current.set(q,d.items)}catch(e){if(!c.signal.aborted&&n===sequence.current)setError(e instanceof Error?e.message:'Catálogo indisponível.')}finally{if(n===sequence.current)setLoading(false)}}
 function choose(item:GifItem){onChoose(item);onClose()}

 return <div className="gif-panel" aria-label="Catálogo de GIFs"><div className="emoji-panel-heading"><strong>GIFs · KLIPY</strong><button type="button" aria-label="Fechar catálogo de GIFs" onClick={onClose}><X size={17}/></button></div><div className="gif-search" onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();void search(query.trim())}}}><input aria-label="Buscar GIFs na KLIPY" placeholder="Search KLIPY" maxLength={100} value={query} onChange={e=>setQuery(e.target.value)} disabled={choosing}/><button type="button" onClick={()=>void search(query.trim())} className="secondary" disabled={loading||choosing} aria-label="Buscar GIFs"><Search size={18}/></button></div><p className="setting-help">Busque uma reação, como “risada” ou “comemorar”. Selecione e depois envie no chat.</p>{(loading||choosing)&&<p role="status">{choosing?'Preparando GIF…':'Buscando GIFs…'}</p>}{error&&<p className="chat-error" role="alert">{error}</p>}<div className="gif-grid">{items.map(item=><button type="button" key={item.id} disabled={choosing} onClick={()=>void choose(item)} aria-label={'Selecionar '+item.title}><img src={item.url} alt={item.title} loading="lazy" referrerPolicy="no-referrer"/></button>)}</div>{!loading&&!error&&!items.length&&<p className="setting-help">Nenhum GIF encontrado. Tente outro termo.</p>}<p className="gif-attribution">Powered by KLIPY · A busca e as prévias usam o serviço externo.</p></div>
}
