'use client';
import {useEffect,useId,useState,type ReactNode} from 'react';
import {MoreHorizontal,VolumeX,MonitorUp,EyeOff,RotateCcw,Check,Flag,Mic,MicOff,Camera,CameraOff,MonitorOff,Settings2} from 'lucide-react';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {participantDefaults,type ParticipantPrefs} from './participant-audio';
export default function ParticipantOptions({name,children,prefs,onChange,sharing,onWatch,active,error,onReport}:{name:string;children:ReactNode;prefs:ParticipantPrefs;onChange:(p:Partial<ParticipantPrefs>)=>void;sharing:boolean;onWatch:()=>void;active:boolean;error:string;onReport:()=>void}){
 const [open,setOpen]=useState(false),id=useId();useEffect(()=>{if(!active)setOpen(false)},[active]);
 return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button type="button" className={'person person-options-trigger '+(prefs.muted?'locally-muted':'')} aria-label={`Opções de ${name}`} title={`Opções de ${name}`}>{children}<span className="person-local-state">{prefs.muted&&<VolumeX size={15} aria-label="Silenciado para você"/>}{prefs.hideCamera&&<EyeOff size={15} aria-label="Câmera oculta para você"/>}<MoreHorizontal size={18}/></span></button></PopoverTrigger><PopoverContent className="participant-menu" align="end" collisionPadding={12} aria-label={`Opções de ${name}`}><h3>{name}</h3><p>Estes ajustes afetam apenas o que você ouve e vê.</p><label htmlFor={id+'-voice'}>Volume da voz <output>{prefs.voice}%</output></label><input id={id+'-voice'} type="range" min="0" max="100" step="1" value={prefs.voice} disabled={prefs.muted} onChange={e=>onChange({voice:Number(e.target.value)})}/><label htmlFor={id+'-screen'}>Som do compartilhamento <output>{prefs.screen}%</output></label><input id={id+'-screen'} type="range" min="0" max="100" step="1" value={prefs.screen} disabled={prefs.muted} onChange={e=>onChange({screen:Number(e.target.value)})}/><small>O volume geral das Configurações também se aplica.</small><button type="button" className="participant-action" aria-pressed={prefs.muted} onClick={()=>onChange({muted:!prefs.muted})}><VolumeX size={17}/><span>{prefs.muted?'Voltar a ouvir':'Silenciar para mim'}</span>{prefs.muted&&<Check size={16}/>}</button><button type="button" className="participant-action" aria-pressed={prefs.hideCamera} onClick={()=>onChange({hideCamera:!prefs.hideCamera})}><EyeOff size={17}/><span>{prefs.hideCamera?'Mostrar câmera':'Ocultar câmera para mim'}</span></button><button type="button" className="participant-action" disabled={!sharing} onClick={()=>{onWatch();setOpen(false)}}><MonitorUp size={17}/><span>{sharing?'Assistir à tela':'Não está compartilhando tela'}</span></button><button type="button" className="participant-action" onClick={()=>{setOpen(false);onReport()}}><Flag size={16}/> Denunciar participante</button><button type="button" className="participant-action participant-reset" onClick={()=>onChange(participantDefaults)}><RotateCcw size={16}/> Restaurar ajustes</button>{error&&<p role="alert" className="chat-error">{error}</p>}</PopoverContent></Popover>;
}

export function SelfOptions({name,children,active,canSend,mic,camera,screen,busy,screenBusy,onMic,onCamera,onScreen,onSettings}:{name:string;children:ReactNode;active:boolean;canSend:boolean;mic:boolean;camera:boolean;screen:boolean;busy:boolean;screenBusy:boolean;onMic:()=>void;onCamera:()=>void;onScreen:()=>void;onSettings:()=>void}){
 const [open,setOpen]=useState(false);useEffect(()=>{if(!active)setOpen(false)},[active]);
 return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button type="button" className="person person-options-trigger" aria-label={`Suas opções, ${name}`} title="Suas opções">{children}<span className="person-local-state"><MoreHorizontal size={18}/></span></button></PopoverTrigger><PopoverContent className="participant-menu" align="end" collisionPadding={12} aria-label="Suas opções"><h3>{name} (você)</h3><p>{canSend?'Controle o que você transmite para a sala.':'Você está na plateia. Pode ouvir e ajustar seus dispositivos.'}</p>{canSend&&<><button type="button" className="participant-action" disabled={busy||!active} aria-pressed={mic} onClick={onMic}>{mic?<MicOff size={17}/>:<Mic size={17}/>}<span>{mic?'Silenciar meu microfone':'Ligar meu microfone'}</span></button><button type="button" className="participant-action" disabled={busy||!active} aria-pressed={camera} onClick={onCamera}>{camera?<CameraOff size={17}/>:<Camera size={17}/>}<span>{camera?'Desligar minha câmera':'Ligar minha câmera'}</span></button><button type="button" className="participant-action" disabled={screenBusy||!active} aria-pressed={screen} onClick={()=>{setOpen(false);onScreen()}}>{screen?<MonitorOff size={17}/>:<MonitorUp size={17}/>}<span>{screen?'Parar minha transmissão':'Compartilhar minha tela'}</span></button></>}<button type="button" className="participant-action" onClick={()=>{setOpen(false);onSettings()}}><Settings2 size={17}/><span>Configurar e testar meus dispositivos</span></button></PopoverContent></Popover>;
}
