'use client';
import {useEffect,useRef} from 'react';
import {Camera,Mic,Headphones,Volume2,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import type {DevicesController} from './use-devices';
export function CameraView({stream,mirror=false}:{stream:MediaStream;mirror?:boolean}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{const el=ref.current;if(el){el.srcObject=stream;void el.play().catch(()=>{})}return()=>{if(el)el.srcObject=null}},[stream]);return <video ref={ref} autoPlay muted playsInline style={{transform:mirror?'scaleX(-1)':undefined}}/>}
function DeviceSelect({label,kind,value,onChange,devices,disabled}:{label:string;kind:MediaDeviceKind;value:string;onChange:(value:string)=>void;devices:MediaDeviceInfo[];disabled?:boolean}){const choices=devices.filter(d=>d.kind===kind&&d.deviceId&&d.deviceId!=='default');return <div className="device-field"><label>{label}</label><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="default">Padrão do sistema</SelectItem>{choices.map((d,i)=><SelectItem key={d.deviceId} value={d.deviceId}>{d.label||`${label} ${i+1}`}</SelectItem>)}{value!=='default'&&!choices.some(d=>d.deviceId===value)&&<SelectItem value={value}>Dispositivo salvo indisponível</SelectItem>}</SelectContent></Select></div>}
function Range({label,value,max=100,onChange}:{label:string;value:number;max?:number;onChange:(n:number)=>void}){return <div className="setting-range"><div><label>{label}</label><output>{value}%</output></div><Slider aria-label={label} value={[value]} min={0} max={max} step={1} onValueChange={v=>onChange(v[0])}/></div>}
function Toggle({label,checked,onChange,disabled}:{label:string;checked:boolean;onChange:(value:boolean)=>void;disabled?:boolean}){return <label className="setting-toggle"><span>{label}</span><Switch checked={checked} onCheckedChange={onChange} disabled={disabled} aria-label={label}/></label>}
export default function Settings({m}:{m:DevicesController}){return <Dialog open={m.open} onOpenChange={m.setPanel}><DialogContent className="device-dialog"><DialogHeader><DialogTitle>Configurações de voz e vídeo</DialogTitle><DialogDescription>Escolha seus dispositivos e teste antes de transmitir.</DialogDescription></DialogHeader><Tabs defaultValue="microphone"><TabsList className="device-tabs"><TabsTrigger value="microphone"><Mic size={16}/>Microfone</TabsTrigger><TabsTrigger value="camera"><Camera size={16}/>Câmera</TabsTrigger><TabsTrigger value="audio"><Headphones size={16}/>Áudio</TabsTrigger></TabsList>
<TabsContent value="microphone"><DeviceSelect label="Microfone de entrada" kind="audioinput" value={m.prefs.input} onChange={input=>m.update({input})} devices={m.devices} disabled={m.busy}/><Range label="Ganho do microfone" value={m.prefs.gain} max={200} onChange={gain=>m.update({gain})}/><div className="mic-meter"><div><span>Nível de entrada</span><span>{m.level>=95?'Muito alto — diminua o ganho':m.testing||m.mic?'Fale para testar':'Teste desligado'}</span></div><meter aria-label="Nível do microfone" min="0" max="100" low={3} high={90} optimum={50} value={m.level}/></div><div className="setting-switches"><Toggle label="Redução de ruído" checked={m.prefs.noise} onChange={noise=>m.update({noise})}/><Toggle label="Cancelamento de eco" checked={m.prefs.echo} onChange={echo=>m.update({echo})}/><Toggle label="Ganho automático" checked={m.prefs.autoGain} onChange={autoGain=>m.update({autoGain})}/></div><section className="monitor-box"><Toggle label="Atenuar ruído nas pausas" checked={m.prefs.gate} onChange={gate=>m.update({gate})}/><div className="setting-range"><div><label>Limite de abertura da voz</label><output>{m.prefs.gateThreshold} dB</output></div><Slider aria-label="Limite de abertura da voz" value={[m.prefs.gateThreshold]} min={-70} max={-25} step={1} onValueChange={v=>m.update({gateThreshold:v[0]})}/></div><p>Comece em −50 dB. Aproxime de −25 para cortar mais ruído nas pausas; aproxime de −70 se a voz sair cortada. Sons altos e ruído durante a fala ainda podem passar.</p></section>{m.filterNotice&&<p className="setting-help" role="status">{m.filterNotice}</p>}<div className="setting-actions"><button className="secondary" onClick={m.toggleTest} disabled={m.busy}>{m.testing?'Parar teste':'Testar microfone'}</button><button className="primary" onClick={m.applyMic} disabled={m.busy}>Aplicar entrada e filtros</button></div><p className="setting-help">A seleção da entrada e os filtros valem após aplicar. O ganho e o limite das pausas mudam na hora. A redução de ruído também corta graves abaixo de 85 Hz. O navegador pode limitar os filtros disponíveis.</p><section className="monitor-box"><Toggle label="Ouvir meu próprio microfone" checked={m.listening} onChange={m.toggleListen} disabled={m.busy}/><p>Use fones. O retorno pode ter um pequeno atraso. Ativar este teste não liga seu microfone para a sala.</p><Range label="Volume do retorno" value={m.prefs.monitorVolume} onChange={monitorVolume=>m.update({monitorVolume})}/></section><p className="device-status">{m.mic?'Seu microfone está ligado para a sala.':'Seu microfone não está sendo transmitido para a sala.'}</p></TabsContent>
<TabsContent value="camera"><DeviceSelect label="Câmera" kind="videoinput" value={m.prefs.camera} onChange={camera=>m.update({camera})} devices={m.devices} disabled={m.busy}/><div className="device-field"><label>Resolução desejada</label><Select value={m.prefs.resolution} onValueChange={resolution=>m.update({resolution})}><SelectTrigger aria-label="Resolução da câmera"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="480">480p · Menor uso de internet</SelectItem><SelectItem value="720">720p · Equilibrado</SelectItem><SelectItem value="1080">1080p · Mais detalhes</SelectItem></SelectContent></Select></div><div className="camera-preview">{m.camera?<CameraView stream={m.camera} mirror={m.prefs.mirror}/>:<div><Camera size={36}/><p>Prévia da sua câmera</p></div>}</div><Toggle label="Espelhar minha prévia" checked={m.prefs.mirror} onChange={mirror=>m.update({mirror})}/><div className="setting-actions"><button className="secondary" onClick={m.togglePreview} disabled={m.busy}>{m.camera&&!m.cameraLive?'Parar prévia':'Testar câmera'}</button><button className="primary" onClick={m.applyCamera} disabled={m.busy}>Aplicar câmera</button></div><p className="setting-help">A resolução depende da câmera. Espelhar altera apenas a sua visualização.</p><p className="device-status">{m.cameraLive?'Sua câmera está sendo transmitida para a sala.':'Esta prévia é só sua. Na sala, clique em Ligar câmera para transmitir.'}</p></TabsContent>
<TabsContent value="audio"><DeviceSelect label="Fone ou alto-falante" kind="audiooutput" value={m.prefs.output} onChange={output=>m.update({output})} devices={m.devices} disabled={!m.sinkSupported}/>{!m.sinkSupported&&<p className="setting-help">Este navegador usa a saída padrão do Windows. Altere o dispositivo nas configurações de som do sistema.</p>}<Range label="Volume de saída" value={m.prefs.volume} onChange={volume=>m.update({volume})}/><button className="secondary speaker-test" onClick={m.testSpeaker} disabled={m.busy}><Volume2 size={18}/>Ouvir som de teste</button><p className="setting-help">Controla o áudio dos participantes e das telas compartilhadas. O retorno do seu microfone também acompanha este volume.</p></TabsContent></Tabs>
{m.error&&<div className="error" role="alert">{m.error}</div>}<div className="device-footer"><span>Preferências salvas neste navegador.</span><button className="icon-button" aria-label="Atualizar lista de dispositivos" onClick={m.refresh}><RefreshCw size={17}/></button></div><p className="setting-help">Para exibir os nomes dos dispositivos, autorize o microfone ou a câmera ao testar. Fechar este painel desliga os testes locais.</p></DialogContent></Dialog>}
