'use client';
import {useEffect,useState} from 'react';
import {Users,Server} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
type Friend={id:string;name:string;state:string;outgoing:number};
export default function SocialPanel(){
 const [open,setOpen]=useState(false),[friends,setFriends]=useState<Friend[]>([]),[servers,setServers]=useState<Array<{id:string;title:string}>>([]),[code,setCode]=useState(''),[input,setInput]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function call(body:object){const r=await fetch('/api/friends',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw new Error(d.error);return d}
 async function refresh(){const d=await call({action:'list'});setFriends(d.friends);setCode(d.code);const r=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'my_servers'})});if(r.ok){const data:any=await r.json();setServers(data.rooms)}}
 useEffect(()=>{if(!open)return;let alive=true;const run=()=>void refresh().catch(e=>{if(alive)setError(e.message)});run();const timer=setInterval(run,15000);return()=>{alive=false;clearInterval(timer)}},[open]);
 async function action(body:object){setBusy(true);setError('');try{await call(body);setInput('');await refresh()}catch(e){setError(e instanceof Error?e.message:'Falha ao atualizar.')}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button className="secondary"><Users size={17}/> Amigos e servidores</button></DialogTrigger><DialogContent className="social-dialog"><DialogHeader><DialogTitle>Amigos e servidores</DialogTitle><DialogDescription>Amizades são exclusivas de contas cadastradas. Compartilhe seu código com quem você conhece.</DialogDescription></DialogHeader>{error&&<p role="alert" className="chat-error">{error}</p>}<label className="field">Seu código de amizade<input readOnly value={code} onFocus={e=>e.target.select()}/></label><form onSubmit={e=>{e.preventDefault();void action({action:'request',code:input})}}><label className="field">Adicionar amigo<input value={input} onChange={e=>setInput(e.target.value)} maxLength={16} placeholder="Código de 16 caracteres"/></label><button className="primary" disabled={busy||input.trim().length!==16}>Enviar pedido</button></form><div className="social-list">{friends.length===0&&<p>Nenhum amigo ou pedido ainda.</p>}{friends.map(f=><div key={f.id} className="social-person"><span><strong>{f.name}</strong><small>{f.state==='accepted'?'Amigo':f.outgoing?'Pedido enviado':'Quer ser seu amigo'}</small></span>{f.state==='pending'&&!f.outgoing&&<button className="secondary" disabled={busy} onClick={()=>void action({action:'accept',id:f.id})}>Aceitar</button>}<button className="secondary" disabled={busy} onClick={()=>{if(f.state!=='accepted'||confirm('Remover esta amizade?'))void action({action:'remove',id:f.id})}}>{f.state==='accepted'?'Remover':f.outgoing?'Cancelar':'Recusar'}</button></div>)}</div><h3><Server size={18}/> Salas permanentes</h3><p>Suas salas ficam salvas na conta, mesmo depois de sair.</p>{servers.length===0&&<p>Crie uma sala permanente ou entre em uma pelo convite.</p>}{servers.map(s=><a className="secondary" key={s.id} href={'/#sala='+s.id} onClick={()=>{setOpen(false);location.assign('/#sala='+s.id);location.reload()}}>{s.title} →</a>)}</DialogContent></Dialog>;
}
