'use client';
import {useEffect,useRef,useState} from 'react';
import {acquireMic,AudioPrefs,defaults,mediaError,MicPipeline,normalizePrefs,routeAudio} from './audio';
type Options={onMic:(track:MediaStreamTrack|null)=>Promise<void>;onCamera:(track:MediaStreamTrack|null)=>Promise<void>};
export function useDevices(options:Options){
 const callbacks=useRef(options);callbacks.current=options;
 const [prefs,setPrefs]=useState<AudioPrefs>(defaults),pref=useRef(defaults),[ready,setReady]=useState(false),[open,setOpen]=useState(false),isOpen=useRef(false);
 const [devices,setDevices]=useState<MediaDeviceInfo[]>([]),[sinkSupported,setSinkSupported]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),lock=useRef(false);
 const pipeline=useRef<MicPipeline|null>(null),micStream=useRef<MediaStream|null>(null),micEnabled=useRef(false),[mic,setMic]=useState(false),[testing,setTesting]=useState(false),testRef=useRef(false),[listening,setListening]=useState(false),listenRef=useRef(false),monitor=useRef<HTMLAudioElement|null>(null),[level,setLevel]=useState(0);
 const cameraStream=useRef<MediaStream|null>(null),cameraEnabled=useRef(false),[camera,setCamera]=useState<MediaStream|null>(null),[cameraLive,setCameraLive]=useState(false),cameraPreview=useRef(false),generation=useRef(0),tone=useRef<()=>void>(()=>{});
 async function refresh(){try{if(navigator.mediaDevices?.enumerateDevices)setDevices(await navigator.mediaDevices.enumerateDevices())}catch(e){setError(mediaError(e))}}
 function update(patch:Partial<AudioPrefs>){const next=normalizePrefs({...pref.current,...patch});pref.current=next;setPrefs(next)}
 function stopMonitor(){listenRef.current=false;setListening(false);if(monitor.current){monitor.current.pause();monitor.current.srcObject=null;monitor.current=null}}
 function releaseMic(){pipeline.current?.dispose();pipeline.current=null;micStream.current=null;setLevel(0)}
 function releaseCamera(){cameraStream.current?.getTracks().forEach(t=>t.stop());cameraStream.current=null;setCamera(null)}
 function stopAll(){generation.current++;tone.current();stopMonitor();micEnabled.current=false;cameraEnabled.current=false;testRef.current=false;cameraPreview.current=false;setMic(false);setTesting(false);setCameraLive(false);releaseMic();releaseCamera()}
 function setPanel(value:boolean){isOpen.current=value;setOpen(value);if(!value){generation.current++;tone.current();stopMonitor();testRef.current=false;cameraPreview.current=false;setTesting(false);if(!micEnabled.current)releaseMic();if(!cameraEnabled.current)releaseCamera()}else{setError('');void refresh()}}
 useEffect(()=>{try{const raw=localStorage.getItem('sala-device-preferences');if(raw){const saved=normalizePrefs(JSON.parse(raw));pref.current=saved;setPrefs(saved)}}catch{}setReady(true);setSinkSupported(typeof HTMLMediaElement.prototype.setSinkId==='function');void refresh();const fn=()=>void refresh();navigator.mediaDevices?.addEventListener('devicechange',fn);return()=>{navigator.mediaDevices?.removeEventListener('devicechange',fn);generation.current++;tone.current();monitor.current?.pause();pipeline.current?.dispose();cameraStream.current?.getTracks().forEach(t=>t.stop())}},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('sala-device-preferences',JSON.stringify(prefs))}catch{}pipeline.current?.setGain(prefs.gain);if(monitor.current)void routeAudio(monitor.current,prefs.output,prefs.monitorVolume*prefs.volume/100).catch(e=>{stopMonitor();setError(mediaError(e))})},[prefs,ready]);
 useEffect(()=>{if(!open)return;const timer=setInterval(()=>{const a=pipeline.current?.analyser;if(!a){setLevel(0);return}const data=new Float32Array(a.fftSize);a.getFloatTimeDomainData(data);let peak=0;for(const v of data)peak=Math.max(peak,Math.abs(v));setLevel(Math.min(100,Math.round(peak*100)))},70);return()=>clearInterval(timer)},[open]);
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError(mediaError(e))}finally{lock.current=false;setBusy(false)}}
 async function playMonitor(){const p=pipeline.current;if(!p)return;monitor.current?.pause();const el=new Audio();el.srcObject=p.monitor;monitor.current=el;try{await routeAudio(el,pref.current.output,pref.current.monitorVolume*pref.current.volume/100);await p.context.resume();await el.play();if(monitor.current!==el){el.pause();el.srcObject=null;return}listenRef.current=true;setListening(true)}catch(e){el.pause();el.srcObject=null;if(monitor.current===el)monitor.current=null;listenRef.current=false;setListening(false);throw e}}
 async function ensureMic(force=false){if(pipeline.current&&!force)return;const g=generation.current;const p=await acquireMic(pref.current);if(g!==generation.current){p.dispose();throw new Error('Teste cancelado.');}const old=pipeline.current;const resumeMonitor=listenRef.current;p.setEnabled(micEnabled.current);try{await callbacks.current.onMic(p.out.getAudioTracks()[0]);if(g!==generation.current)throw new Error('Teste cancelado.')}catch(e){p.dispose();throw e}pipeline.current=p;micStream.current=p.out;old?.dispose();p.raw.getAudioTracks()[0].onended=()=>{if(pipeline.current!==p)return;micEnabled.current=false;setMic(false);testRef.current=false;setTesting(false);stopMonitor();releaseMic();void callbacks.current.onMic(null).catch(e=>setError(mediaError(e)));setError('O microfone foi desconectado. Escolha outro dispositivo.')};await refresh();if(resumeMonitor)await playMonitor()}
 async function toggleMic(){await run(async()=>{if(micEnabled.current){micEnabled.current=false;setMic(false);pipeline.current?.setEnabled(false);if(!testRef.current){await callbacks.current.onMic(null);releaseMic()}}else{await ensureMic();if(!pipeline.current)return;await pipeline.current.context.resume();micEnabled.current=true;pipeline.current.setEnabled(true);setMic(true)}})}
 async function toggleTest(){await run(async()=>{if(testRef.current){stopMonitor();testRef.current=false;setTesting(false);if(!micEnabled.current){await callbacks.current.onMic(null);releaseMic()}}else{await ensureMic();testRef.current=true;setTesting(true)}})}
 async function toggleListen(value:boolean){if(!value){stopMonitor();return}await run(async()=>{await ensureMic();testRef.current=true;setTesting(true);await playMonitor()})}
 async function ensureCamera(force=false){if(cameraStream.current&&!force)return;if(!navigator.mediaDevices?.getUserMedia)throw new Error('A câmera precisa do endereço HTTPS do aplicativo.');const g=generation.current,height=Number(pref.current.resolution);const next=await navigator.mediaDevices.getUserMedia({video:{deviceId:pref.current.camera==='default'?undefined:{exact:pref.current.camera},width:{ideal:Math.round(height*16/9)},height:{ideal:height},frameRate:{ideal:30,max:30}},audio:false});if(g!==generation.current){next.getTracks().forEach(t=>t.stop());throw new Error('Prévia cancelada.')}const old=cameraStream.current;try{if(cameraEnabled.current)await callbacks.current.onCamera(next.getVideoTracks()[0]);if(g!==generation.current)throw new Error('Prévia cancelada.')}catch(e){next.getTracks().forEach(t=>t.stop());throw e}cameraStream.current=next;setCamera(next);old?.getTracks().forEach(t=>t.stop());next.getVideoTracks()[0].onended=()=>{if(cameraStream.current!==next)return;cameraEnabled.current=false;setCameraLive(false);releaseCamera();void callbacks.current.onCamera(null).catch(e=>setError(mediaError(e)));setError('A câmera foi desconectada.')};await refresh()}
 async function toggleCamera(){await run(async()=>{if(cameraEnabled.current){cameraEnabled.current=false;setCameraLive(false);await callbacks.current.onCamera(null);if(!cameraPreview.current)releaseCamera()}else{await ensureCamera();if(!cameraStream.current)return;await callbacks.current.onCamera(cameraStream.current.getVideoTracks()[0]);cameraEnabled.current=true;setCameraLive(true)}})}
 async function togglePreview(){await run(async()=>{if(cameraPreview.current){cameraPreview.current=false;if(!cameraEnabled.current)releaseCamera()}else{await ensureCamera();cameraPreview.current=true}})}
 async function applyMic(){await run(async()=>{if(pipeline.current)await ensureMic(true);else{await ensureMic();testRef.current=true;setTesting(true)}})}
 async function applyCamera(){await run(async()=>{await ensureCamera(true);if(!cameraEnabled.current)cameraPreview.current=true})}
 async function testSpeaker(){await run(async()=>{tone.current();const context=new AudioContext();await context.resume();const osc=context.createOscillator(),gain=context.createGain(),destination=context.createMediaStreamDestination(),el=new Audio();let timer:ReturnType<typeof setTimeout>;const stop=()=>{clearTimeout(timer);try{osc.stop()}catch{}el.pause();el.srcObject=null;destination.stream.getTracks().forEach(t=>t.stop());void context.close().catch(()=>{})};tone.current=stop;try{osc.frequency.value=440;gain.gain.value=.12;osc.connect(gain);gain.connect(destination);el.srcObject=destination.stream;await routeAudio(el,pref.current.output,pref.current.volume);await el.play();osc.start();timer=setTimeout(stop,800)}catch(e){stop();throw e}})}
 return {prefs,update,open,setPanel,devices,refresh,sinkSupported,error,setError,busy,mic,micEnabled,micStream,camera,cameraLive,cameraStream,cameraEnabled,testing,listening,level,toggleMic,toggleTest,toggleListen,toggleCamera,togglePreview,applyMic,applyCamera,testSpeaker,stopAll};
}
export type DevicesController=ReturnType<typeof useDevices>;
